// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: order/common.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByIdOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdOrderRequest) Reset() {
	*x = FindByIdOrderRequest{}
	mi := &file_order_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdOrderRequest) ProtoMessage() {}

func (x *FindByIdOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdOrderRequest.ProtoReflect.Descriptor instead.
func (*FindByIdOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_common_proto_rawDescGZIP(), []int{0}
}

func (x *FindByIdOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalPrice    int32                  `protobuf:"varint,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_order_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_order_common_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderResponse) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type OrderResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalPrice    int32                   `protobuf:"varint,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponseDeleteAt) Reset() {
	*x = OrderResponseDeleteAt{}
	mi := &file_order_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponseDeleteAt) ProtoMessage() {}

func (x *OrderResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_order_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*OrderResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_order_common_proto_rawDescGZIP(), []int{2}
}

func (x *OrderResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderResponseDeleteAt) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderResponseDeleteAt) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *OrderResponse         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrder) Reset() {
	*x = ApiResponseOrder{}
	mi := &file_order_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrder) ProtoMessage() {}

func (x *ApiResponseOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrder.ProtoReflect.Descriptor instead.
func (*ApiResponseOrder) Descriptor() ([]byte, []int) {
	return file_order_common_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrder) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrder) GetData() *OrderResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseOrderDeleteAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *OrderResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderDeleteAt) Reset() {
	*x = ApiResponseOrderDeleteAt{}
	mi := &file_order_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderDeleteAt) ProtoMessage() {}

func (x *ApiResponseOrderDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_order_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderDeleteAt) Descriptor() ([]byte, []int) {
	return file_order_common_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseOrderDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrderDeleteAt) GetData() *OrderResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_order_common_proto protoreflect.FileDescriptor

const file_order_common_proto_rawDesc = "" +
	"\n" +
	"\x12order/common.proto\x12\bpb.order\x1a\x1egoogle/protobuf/wrappers.proto\"&\n" +
	"\x14FindByIdOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x97\x01\n" +
	"\rOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x05R\n" +
	"totalPrice\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"\xdc\x01\n" +
	"\x15OrderResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x05R\n" +
	"totalPrice\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"q\n" +
	"\x10ApiResponseOrder\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.pb.order.OrderResponseR\x04data\"\x81\x01\n" +
	"\x18ApiResponseOrderDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.pb.order.OrderResponseDeleteAtR\x04dataB>Z<github.com/MamangRust/simple_microservice_ecommerce_pb/orderb\x06proto3"

var (
	file_order_common_proto_rawDescOnce sync.Once
	file_order_common_proto_rawDescData []byte
)

func file_order_common_proto_rawDescGZIP() []byte {
	file_order_common_proto_rawDescOnce.Do(func() {
		file_order_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_common_proto_rawDesc), len(file_order_common_proto_rawDesc)))
	})
	return file_order_common_proto_rawDescData
}

var file_order_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_order_common_proto_goTypes = []any{
	(*FindByIdOrderRequest)(nil),     // 0: pb.order.FindByIdOrderRequest
	(*OrderResponse)(nil),            // 1: pb.order.OrderResponse
	(*OrderResponseDeleteAt)(nil),    // 2: pb.order.OrderResponseDeleteAt
	(*ApiResponseOrder)(nil),         // 3: pb.order.ApiResponseOrder
	(*ApiResponseOrderDeleteAt)(nil), // 4: pb.order.ApiResponseOrderDeleteAt
	(*wrapperspb.StringValue)(nil),   // 5: google.protobuf.StringValue
}
var file_order_common_proto_depIdxs = []int32{
	5, // 0: pb.order.OrderResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	1, // 1: pb.order.ApiResponseOrder.data:type_name -> pb.order.OrderResponse
	2, // 2: pb.order.ApiResponseOrderDeleteAt.data:type_name -> pb.order.OrderResponseDeleteAt
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_order_common_proto_init() }
func file_order_common_proto_init() {
	if File_order_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_common_proto_rawDesc), len(file_order_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_common_proto_goTypes,
		DependencyIndexes: file_order_common_proto_depIdxs,
		MessageInfos:      file_order_common_proto_msgTypes,
	}.Build()
	File_order_common_proto = out.File
	file_order_common_proto_goTypes = nil
	file_order_common_proto_depIdxs = nil
}
