// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: order/command.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderCommandService_Create_FullMethodName               = "/pb.order.OrderCommandService/Create"
	OrderCommandService_Update_FullMethodName               = "/pb.order.OrderCommandService/Update"
	OrderCommandService_Trashed_FullMethodName              = "/pb.order.OrderCommandService/Trashed"
	OrderCommandService_Restore_FullMethodName              = "/pb.order.OrderCommandService/Restore"
	OrderCommandService_DeleteOrderPermanent_FullMethodName = "/pb.order.OrderCommandService/DeleteOrderPermanent"
	OrderCommandService_RestoreAllOrder_FullMethodName      = "/pb.order.OrderCommandService/RestoreAllOrder"
	OrderCommandService_DeleteAllOrder_FullMethodName       = "/pb.order.OrderCommandService/DeleteAllOrder"
)

// OrderCommandServiceClient is the client API for OrderCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderCommandServiceClient interface {
	Create(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrder, error)
	Update(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrder, error)
	Trashed(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrderDeleteAt, error)
	Restore(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrderDeleteAt, error)
	DeleteOrderPermanent(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrderDelete, error)
	RestoreAllOrder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseOrderAll, error)
	DeleteAllOrder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseOrderAll, error)
}

type orderCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderCommandServiceClient(cc grpc.ClientConnInterface) OrderCommandServiceClient {
	return &orderCommandServiceClient{cc}
}

func (c *orderCommandServiceClient) Create(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrder)
	err := c.cc.Invoke(ctx, OrderCommandService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCommandServiceClient) Update(ctx context.Context, in *UpdateOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrder)
	err := c.cc.Invoke(ctx, OrderCommandService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCommandServiceClient) Trashed(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrderDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderDeleteAt)
	err := c.cc.Invoke(ctx, OrderCommandService_Trashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCommandServiceClient) Restore(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrderDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderDeleteAt)
	err := c.cc.Invoke(ctx, OrderCommandService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCommandServiceClient) DeleteOrderPermanent(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrderDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderDelete)
	err := c.cc.Invoke(ctx, OrderCommandService_DeleteOrderPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCommandServiceClient) RestoreAllOrder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseOrderAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderAll)
	err := c.cc.Invoke(ctx, OrderCommandService_RestoreAllOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderCommandServiceClient) DeleteAllOrder(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseOrderAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrderAll)
	err := c.cc.Invoke(ctx, OrderCommandService_DeleteAllOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderCommandServiceServer is the server API for OrderCommandService service.
// All implementations must embed UnimplementedOrderCommandServiceServer
// for forward compatibility.
type OrderCommandServiceServer interface {
	Create(context.Context, *CreateOrderRequest) (*ApiResponseOrder, error)
	Update(context.Context, *UpdateOrderRequest) (*ApiResponseOrder, error)
	Trashed(context.Context, *FindByIdOrderRequest) (*ApiResponseOrderDeleteAt, error)
	Restore(context.Context, *FindByIdOrderRequest) (*ApiResponseOrderDeleteAt, error)
	DeleteOrderPermanent(context.Context, *FindByIdOrderRequest) (*ApiResponseOrderDelete, error)
	RestoreAllOrder(context.Context, *emptypb.Empty) (*ApiResponseOrderAll, error)
	DeleteAllOrder(context.Context, *emptypb.Empty) (*ApiResponseOrderAll, error)
	mustEmbedUnimplementedOrderCommandServiceServer()
}

// UnimplementedOrderCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderCommandServiceServer struct{}

func (UnimplementedOrderCommandServiceServer) Create(context.Context, *CreateOrderRequest) (*ApiResponseOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOrderCommandServiceServer) Update(context.Context, *UpdateOrderRequest) (*ApiResponseOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedOrderCommandServiceServer) Trashed(context.Context, *FindByIdOrderRequest) (*ApiResponseOrderDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trashed not implemented")
}
func (UnimplementedOrderCommandServiceServer) Restore(context.Context, *FindByIdOrderRequest) (*ApiResponseOrderDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedOrderCommandServiceServer) DeleteOrderPermanent(context.Context, *FindByIdOrderRequest) (*ApiResponseOrderDelete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrderPermanent not implemented")
}
func (UnimplementedOrderCommandServiceServer) RestoreAllOrder(context.Context, *emptypb.Empty) (*ApiResponseOrderAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreAllOrder not implemented")
}
func (UnimplementedOrderCommandServiceServer) DeleteAllOrder(context.Context, *emptypb.Empty) (*ApiResponseOrderAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllOrder not implemented")
}
func (UnimplementedOrderCommandServiceServer) mustEmbedUnimplementedOrderCommandServiceServer() {}
func (UnimplementedOrderCommandServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrderCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderCommandServiceServer will
// result in compilation errors.
type UnsafeOrderCommandServiceServer interface {
	mustEmbedUnimplementedOrderCommandServiceServer()
}

func RegisterOrderCommandServiceServer(s grpc.ServiceRegistrar, srv OrderCommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderCommandService_ServiceDesc, srv)
}

func _OrderCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCommandService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCommandServiceServer).Create(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCommandService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCommandServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCommandService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCommandServiceServer).Update(ctx, req.(*UpdateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCommandService_Trashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCommandServiceServer).Trashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCommandService_Trashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCommandServiceServer).Trashed(ctx, req.(*FindByIdOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCommandService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCommandServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCommandService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCommandServiceServer).Restore(ctx, req.(*FindByIdOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCommandService_DeleteOrderPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCommandServiceServer).DeleteOrderPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCommandService_DeleteOrderPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCommandServiceServer).DeleteOrderPermanent(ctx, req.(*FindByIdOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCommandService_RestoreAllOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCommandServiceServer).RestoreAllOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCommandService_RestoreAllOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCommandServiceServer).RestoreAllOrder(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderCommandService_DeleteAllOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderCommandServiceServer).DeleteAllOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderCommandService_DeleteAllOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderCommandServiceServer).DeleteAllOrder(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderCommandService_ServiceDesc is the grpc.ServiceDesc for OrderCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.order.OrderCommandService",
	HandlerType: (*OrderCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrderCommandService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _OrderCommandService_Update_Handler,
		},
		{
			MethodName: "Trashed",
			Handler:    _OrderCommandService_Trashed_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _OrderCommandService_Restore_Handler,
		},
		{
			MethodName: "DeleteOrderPermanent",
			Handler:    _OrderCommandService_DeleteOrderPermanent_Handler,
		},
		{
			MethodName: "RestoreAllOrder",
			Handler:    _OrderCommandService_RestoreAllOrder_Handler,
		},
		{
			MethodName: "DeleteAllOrder",
			Handler:    _OrderCommandService_DeleteAllOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/command.proto",
}
