// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: order/command.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemRequest) Reset() {
	*x = CreateOrderItemRequest{}
	mi := &file_order_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemRequest) ProtoMessage() {}

func (x *CreateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_order_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderItemRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderItemRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderItemId   int32                  `protobuf:"varint,1,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderItemRequest) Reset() {
	*x = UpdateOrderItemRequest{}
	mi := &file_order_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderItemRequest) ProtoMessage() {}

func (x *UpdateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_order_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateOrderItemRequest) GetOrderItemId() int32 {
	if x != nil {
		return x.OrderItemId
	}
	return 0
}

func (x *UpdateOrderItemRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *UpdateOrderItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateOrderItemRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	UserId        int32                     `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*CreateOrderItemRequest `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_command_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderRequest) GetItems() []*CreateOrderItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	OrderId       int32                     `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        int32                     `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*UpdateOrderItemRequest `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_order_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_command_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateOrderRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateOrderRequest) GetItems() []*UpdateOrderItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type ApiResponseOrderDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderDelete) Reset() {
	*x = ApiResponseOrderDelete{}
	mi := &file_order_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderDelete) ProtoMessage() {}

func (x *ApiResponseOrderDelete) ProtoReflect() protoreflect.Message {
	mi := &file_order_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderDelete) Descriptor() ([]byte, []int) {
	return file_order_command_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseOrderDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseOrderAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderAll) Reset() {
	*x = ApiResponseOrderAll{}
	mi := &file_order_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderAll) ProtoMessage() {}

func (x *ApiResponseOrderAll) ProtoReflect() protoreflect.Message {
	mi := &file_order_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderAll.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderAll) Descriptor() ([]byte, []int) {
	return file_order_command_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseOrderAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_order_command_proto protoreflect.FileDescriptor

const file_order_command_proto_rawDesc = "" +
	"\n" +
	"\x13order/command.proto\x12\bpb.order\x1a\x1bgoogle/protobuf/empty.proto\x1a\x12order/common.proto\"i\n" +
	"\x16CreateOrderItemRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\"\x8d\x01\n" +
	"\x16UpdateOrderItemRequest\x12\"\n" +
	"\rorder_item_id\x18\x01 \x01(\x05R\vorderItemId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\"e\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x126\n" +
	"\x05items\x18\x02 \x03(\v2 .pb.order.CreateOrderItemRequestR\x05items\"\x80\x01\n" +
	"\x12UpdateOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x126\n" +
	"\x05items\x18\x03 \x03(\v2 .pb.order.UpdateOrderItemRequestR\x05items\"J\n" +
	"\x16ApiResponseOrderDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\x13ApiResponseOrderAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xa8\x04\n" +
	"\x13OrderCommandService\x12B\n" +
	"\x06Create\x12\x1c.pb.order.CreateOrderRequest\x1a\x1a.pb.order.ApiResponseOrder\x12B\n" +
	"\x06Update\x12\x1c.pb.order.UpdateOrderRequest\x1a\x1a.pb.order.ApiResponseOrder\x12M\n" +
	"\aTrashed\x12\x1e.pb.order.FindByIdOrderRequest\x1a\".pb.order.ApiResponseOrderDeleteAt\x12M\n" +
	"\aRestore\x12\x1e.pb.order.FindByIdOrderRequest\x1a\".pb.order.ApiResponseOrderDeleteAt\x12X\n" +
	"\x14DeleteOrderPermanent\x12\x1e.pb.order.FindByIdOrderRequest\x1a .pb.order.ApiResponseOrderDelete\x12H\n" +
	"\x0fRestoreAllOrder\x12\x16.google.protobuf.Empty\x1a\x1d.pb.order.ApiResponseOrderAll\x12G\n" +
	"\x0eDeleteAllOrder\x12\x16.google.protobuf.Empty\x1a\x1d.pb.order.ApiResponseOrderAllB>Z<github.com/MamangRust/simple_microservice_ecommerce_pb/orderb\x06proto3"

var (
	file_order_command_proto_rawDescOnce sync.Once
	file_order_command_proto_rawDescData []byte
)

func file_order_command_proto_rawDescGZIP() []byte {
	file_order_command_proto_rawDescOnce.Do(func() {
		file_order_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_command_proto_rawDesc), len(file_order_command_proto_rawDesc)))
	})
	return file_order_command_proto_rawDescData
}

var file_order_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_order_command_proto_goTypes = []any{
	(*CreateOrderItemRequest)(nil),   // 0: pb.order.CreateOrderItemRequest
	(*UpdateOrderItemRequest)(nil),   // 1: pb.order.UpdateOrderItemRequest
	(*CreateOrderRequest)(nil),       // 2: pb.order.CreateOrderRequest
	(*UpdateOrderRequest)(nil),       // 3: pb.order.UpdateOrderRequest
	(*ApiResponseOrderDelete)(nil),   // 4: pb.order.ApiResponseOrderDelete
	(*ApiResponseOrderAll)(nil),      // 5: pb.order.ApiResponseOrderAll
	(*FindByIdOrderRequest)(nil),     // 6: pb.order.FindByIdOrderRequest
	(*emptypb.Empty)(nil),            // 7: google.protobuf.Empty
	(*ApiResponseOrder)(nil),         // 8: pb.order.ApiResponseOrder
	(*ApiResponseOrderDeleteAt)(nil), // 9: pb.order.ApiResponseOrderDeleteAt
}
var file_order_command_proto_depIdxs = []int32{
	0, // 0: pb.order.CreateOrderRequest.items:type_name -> pb.order.CreateOrderItemRequest
	1, // 1: pb.order.UpdateOrderRequest.items:type_name -> pb.order.UpdateOrderItemRequest
	2, // 2: pb.order.OrderCommandService.Create:input_type -> pb.order.CreateOrderRequest
	3, // 3: pb.order.OrderCommandService.Update:input_type -> pb.order.UpdateOrderRequest
	6, // 4: pb.order.OrderCommandService.Trashed:input_type -> pb.order.FindByIdOrderRequest
	6, // 5: pb.order.OrderCommandService.Restore:input_type -> pb.order.FindByIdOrderRequest
	6, // 6: pb.order.OrderCommandService.DeleteOrderPermanent:input_type -> pb.order.FindByIdOrderRequest
	7, // 7: pb.order.OrderCommandService.RestoreAllOrder:input_type -> google.protobuf.Empty
	7, // 8: pb.order.OrderCommandService.DeleteAllOrder:input_type -> google.protobuf.Empty
	8, // 9: pb.order.OrderCommandService.Create:output_type -> pb.order.ApiResponseOrder
	8, // 10: pb.order.OrderCommandService.Update:output_type -> pb.order.ApiResponseOrder
	9, // 11: pb.order.OrderCommandService.Trashed:output_type -> pb.order.ApiResponseOrderDeleteAt
	9, // 12: pb.order.OrderCommandService.Restore:output_type -> pb.order.ApiResponseOrderDeleteAt
	4, // 13: pb.order.OrderCommandService.DeleteOrderPermanent:output_type -> pb.order.ApiResponseOrderDelete
	5, // 14: pb.order.OrderCommandService.RestoreAllOrder:output_type -> pb.order.ApiResponseOrderAll
	5, // 15: pb.order.OrderCommandService.DeleteAllOrder:output_type -> pb.order.ApiResponseOrderAll
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_order_command_proto_init() }
func file_order_command_proto_init() {
	if File_order_command_proto != nil {
		return
	}
	file_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_command_proto_rawDesc), len(file_order_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_command_proto_goTypes,
		DependencyIndexes: file_order_command_proto_depIdxs,
		MessageInfos:      file_order_command_proto_msgTypes,
	}.Build()
	File_order_command_proto = out.File
	file_order_command_proto_goTypes = nil
	file_order_command_proto_depIdxs = nil
}
