// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: order/query.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderQueryService_FindAll_FullMethodName       = "/pb.order.OrderQueryService/FindAll"
	OrderQueryService_FindById_FullMethodName      = "/pb.order.OrderQueryService/FindById"
	OrderQueryService_FindByActive_FullMethodName  = "/pb.order.OrderQueryService/FindByActive"
	OrderQueryService_FindByTrashed_FullMethodName = "/pb.order.OrderQueryService/FindByTrashed"
)

// OrderQueryServiceClient is the client API for OrderQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderQueryServiceClient interface {
	FindAll(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrder, error)
	FindById(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrder, error)
	FindByActive(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderDeleteAt, error)
	FindByTrashed(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderDeleteAt, error)
}

type orderQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderQueryServiceClient(cc grpc.ClientConnInterface) OrderQueryServiceClient {
	return &orderQueryServiceClient{cc}
}

func (c *orderQueryServiceClient) FindAll(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrder)
	err := c.cc.Invoke(ctx, OrderQueryService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindById(ctx context.Context, in *FindByIdOrderRequest, opts ...grpc.CallOption) (*ApiResponseOrder, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseOrder)
	err := c.cc.Invoke(ctx, OrderQueryService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindByActive(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrderDeleteAt)
	err := c.cc.Invoke(ctx, OrderQueryService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderQueryServiceClient) FindByTrashed(ctx context.Context, in *FindAllOrderRequest, opts ...grpc.CallOption) (*ApiResponsePaginationOrderDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationOrderDeleteAt)
	err := c.cc.Invoke(ctx, OrderQueryService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderQueryServiceServer is the server API for OrderQueryService service.
// All implementations must embed UnimplementedOrderQueryServiceServer
// for forward compatibility.
type OrderQueryServiceServer interface {
	FindAll(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrder, error)
	FindById(context.Context, *FindByIdOrderRequest) (*ApiResponseOrder, error)
	FindByActive(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrderDeleteAt, error)
	FindByTrashed(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrderDeleteAt, error)
	mustEmbedUnimplementedOrderQueryServiceServer()
}

// UnimplementedOrderQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderQueryServiceServer struct{}

func (UnimplementedOrderQueryServiceServer) FindAll(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindById(context.Context, *FindByIdOrderRequest) (*ApiResponseOrder, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindByActive(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrderDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedOrderQueryServiceServer) FindByTrashed(context.Context, *FindAllOrderRequest) (*ApiResponsePaginationOrderDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedOrderQueryServiceServer) mustEmbedUnimplementedOrderQueryServiceServer() {}
func (UnimplementedOrderQueryServiceServer) testEmbeddedByValue()                           {}

// UnsafeOrderQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderQueryServiceServer will
// result in compilation errors.
type UnsafeOrderQueryServiceServer interface {
	mustEmbedUnimplementedOrderQueryServiceServer()
}

func RegisterOrderQueryServiceServer(s grpc.ServiceRegistrar, srv OrderQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderQueryService_ServiceDesc, srv)
}

func _OrderQueryService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindAll(ctx, req.(*FindAllOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindById(ctx, req.(*FindByIdOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindByActive(ctx, req.(*FindAllOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderQueryService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderQueryServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderQueryService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderQueryServiceServer).FindByTrashed(ctx, req.(*FindAllOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderQueryService_ServiceDesc is the grpc.ServiceDesc for OrderQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.order.OrderQueryService",
	HandlerType: (*OrderQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _OrderQueryService_FindAll_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _OrderQueryService_FindById_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _OrderQueryService_FindByActive_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _OrderQueryService_FindByTrashed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/query.proto",
}
