// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: order/query.proto

package order

import (
	simple_microservice_ecommerce_pb "github.com/MamangRust/simple_microservice_ecommerce_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrderRequest) Reset() {
	*x = FindAllOrderRequest{}
	mi := &file_order_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrderRequest) ProtoMessage() {}

func (x *FindAllOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrderRequest.ProtoReflect.Descriptor instead.
func (*FindAllOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllOrderRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllOrderRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllOrderRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ApiResponsePaginationOrderDeleteAt struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Status        string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderResponseDeleteAt                     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationOrderDeleteAt) Reset() {
	*x = ApiResponsePaginationOrderDeleteAt{}
	mi := &file_order_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationOrderDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationOrderDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationOrderDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationOrderDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationOrderDeleteAt) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponsePaginationOrderDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationOrderDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationOrderDeleteAt) GetData() []*OrderResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationOrderDeleteAt) GetPagination() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationOrder struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Status        string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderResponse                             `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationOrder) Reset() {
	*x = ApiResponsePaginationOrder{}
	mi := &file_order_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationOrder) ProtoMessage() {}

func (x *ApiResponsePaginationOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationOrder.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationOrder) Descriptor() ([]byte, []int) {
	return file_order_query_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponsePaginationOrder) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationOrder) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationOrder) GetData() []*OrderResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationOrder) GetPagination() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_order_query_proto protoreflect.FileDescriptor

const file_order_query_proto_rawDesc = "" +
	"\n" +
	"\x11order/query.proto\x12\bpb.order\x1a\tapi.proto\x1a\x12order/common.proto\"^\n" +
	"\x13FindAllOrderRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\xbb\x01\n" +
	"\"ApiResponsePaginationOrderDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x03(\v2\x1f.pb.order.OrderResponseDeleteAtR\x04data\x12.\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination\"\xab\x01\n" +
	"\x1aApiResponsePaginationOrder\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.pb.order.OrderResponseR\x04data\x12.\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination2\xe6\x02\n" +
	"\x11OrderQueryService\x12N\n" +
	"\aFindAll\x12\x1d.pb.order.FindAllOrderRequest\x1a$.pb.order.ApiResponsePaginationOrder\x12F\n" +
	"\bFindById\x12\x1e.pb.order.FindByIdOrderRequest\x1a\x1a.pb.order.ApiResponseOrder\x12[\n" +
	"\fFindByActive\x12\x1d.pb.order.FindAllOrderRequest\x1a,.pb.order.ApiResponsePaginationOrderDeleteAt\x12\\\n" +
	"\rFindByTrashed\x12\x1d.pb.order.FindAllOrderRequest\x1a,.pb.order.ApiResponsePaginationOrderDeleteAtB>Z<github.com/MamangRust/simple_microservice_ecommerce_pb/orderb\x06proto3"

var (
	file_order_query_proto_rawDescOnce sync.Once
	file_order_query_proto_rawDescData []byte
)

func file_order_query_proto_rawDescGZIP() []byte {
	file_order_query_proto_rawDescOnce.Do(func() {
		file_order_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_query_proto_rawDesc), len(file_order_query_proto_rawDesc)))
	})
	return file_order_query_proto_rawDescData
}

var file_order_query_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_order_query_proto_goTypes = []any{
	(*FindAllOrderRequest)(nil),                         // 0: pb.order.FindAllOrderRequest
	(*ApiResponsePaginationOrderDeleteAt)(nil),          // 1: pb.order.ApiResponsePaginationOrderDeleteAt
	(*ApiResponsePaginationOrder)(nil),                  // 2: pb.order.ApiResponsePaginationOrder
	(*OrderResponseDeleteAt)(nil),                       // 3: pb.order.OrderResponseDeleteAt
	(*simple_microservice_ecommerce_pb.Pagination)(nil), // 4: pb.Pagination
	(*OrderResponse)(nil),                               // 5: pb.order.OrderResponse
	(*FindByIdOrderRequest)(nil),                        // 6: pb.order.FindByIdOrderRequest
	(*ApiResponseOrder)(nil),                            // 7: pb.order.ApiResponseOrder
}
var file_order_query_proto_depIdxs = []int32{
	3, // 0: pb.order.ApiResponsePaginationOrderDeleteAt.data:type_name -> pb.order.OrderResponseDeleteAt
	4, // 1: pb.order.ApiResponsePaginationOrderDeleteAt.pagination:type_name -> pb.Pagination
	5, // 2: pb.order.ApiResponsePaginationOrder.data:type_name -> pb.order.OrderResponse
	4, // 3: pb.order.ApiResponsePaginationOrder.pagination:type_name -> pb.Pagination
	0, // 4: pb.order.OrderQueryService.FindAll:input_type -> pb.order.FindAllOrderRequest
	6, // 5: pb.order.OrderQueryService.FindById:input_type -> pb.order.FindByIdOrderRequest
	0, // 6: pb.order.OrderQueryService.FindByActive:input_type -> pb.order.FindAllOrderRequest
	0, // 7: pb.order.OrderQueryService.FindByTrashed:input_type -> pb.order.FindAllOrderRequest
	2, // 8: pb.order.OrderQueryService.FindAll:output_type -> pb.order.ApiResponsePaginationOrder
	7, // 9: pb.order.OrderQueryService.FindById:output_type -> pb.order.ApiResponseOrder
	1, // 10: pb.order.OrderQueryService.FindByActive:output_type -> pb.order.ApiResponsePaginationOrderDeleteAt
	1, // 11: pb.order.OrderQueryService.FindByTrashed:output_type -> pb.order.ApiResponsePaginationOrderDeleteAt
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_order_query_proto_init() }
func file_order_query_proto_init() {
	if File_order_query_proto != nil {
		return
	}
	file_order_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_query_proto_rawDesc), len(file_order_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_query_proto_goTypes,
		DependencyIndexes: file_order_query_proto_depIdxs,
		MessageInfos:      file_order_query_proto_msgTypes,
	}.Build()
	File_order_query_proto = out.File
	file_order_query_proto_goTypes = nil
	file_order_query_proto_depIdxs = nil
}
