// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: user_role/user_role.proto

package user_role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        int32                  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Roleid        int32                  `protobuf:"varint,2,opt,name=roleid,proto3" json:"roleid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRoleRequest) Reset() {
	*x = CreateUserRoleRequest{}
	mi := &file_user_role_user_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRoleRequest) ProtoMessage() {}

func (x *CreateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_role_user_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_user_role_user_role_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRoleRequest) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *CreateUserRoleRequest) GetRoleid() int32 {
	if x != nil {
		return x.Roleid
	}
	return 0
}

type UserRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        int32                  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Roleid        int32                  `protobuf:"varint,2,opt,name=roleid,proto3" json:"roleid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRoleResponse) Reset() {
	*x = UserRoleResponse{}
	mi := &file_user_role_user_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleResponse) ProtoMessage() {}

func (x *UserRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_role_user_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleResponse.ProtoReflect.Descriptor instead.
func (*UserRoleResponse) Descriptor() ([]byte, []int) {
	return file_user_role_user_role_proto_rawDescGZIP(), []int{1}
}

func (x *UserRoleResponse) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *UserRoleResponse) GetRoleid() int32 {
	if x != nil {
		return x.Roleid
	}
	return 0
}

type ApiResponseUserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserRoleResponse      `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseUserRole) Reset() {
	*x = ApiResponseUserRole{}
	mi := &file_user_role_user_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseUserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseUserRole) ProtoMessage() {}

func (x *ApiResponseUserRole) ProtoReflect() protoreflect.Message {
	mi := &file_user_role_user_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseUserRole.ProtoReflect.Descriptor instead.
func (*ApiResponseUserRole) Descriptor() ([]byte, []int) {
	return file_user_role_user_role_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseUserRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseUserRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseUserRole) GetData() *UserRoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_user_role_user_role_proto protoreflect.FileDescriptor

const file_user_role_user_role_proto_rawDesc = "" +
	"\n" +
	"\x19user_role/user_role.proto\x12\fpb.user_role\"G\n" +
	"\x15CreateUserRoleRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\x05R\x06userid\x12\x16\n" +
	"\x06roleid\x18\x02 \x01(\x05R\x06roleid\"B\n" +
	"\x10UserRoleResponse\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\x05R\x06userid\x12\x16\n" +
	"\x06roleid\x18\x02 \x01(\x05R\x06roleid\"{\n" +
	"\x13ApiResponseUserRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x04data\x18\x03 \x01(\v2\x1e.pb.user_role.UserRoleResponseR\x04data2\xbd\x01\n" +
	"\x0fUserRoleService\x12T\n" +
	"\n" +
	"AssignRole\x12#.pb.user_role.CreateUserRoleRequest\x1a!.pb.user_role.ApiResponseUserRole\x12T\n" +
	"\n" +
	"UpdateRole\x12#.pb.user_role.CreateUserRoleRequest\x1a!.pb.user_role.ApiResponseUserRoleBBZ@github.com/MamangRust/simple_microservice_ecommerce_pb/user_roleb\x06proto3"

var (
	file_user_role_user_role_proto_rawDescOnce sync.Once
	file_user_role_user_role_proto_rawDescData []byte
)

func file_user_role_user_role_proto_rawDescGZIP() []byte {
	file_user_role_user_role_proto_rawDescOnce.Do(func() {
		file_user_role_user_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_role_user_role_proto_rawDesc), len(file_user_role_user_role_proto_rawDesc)))
	})
	return file_user_role_user_role_proto_rawDescData
}

var file_user_role_user_role_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_role_user_role_proto_goTypes = []any{
	(*CreateUserRoleRequest)(nil), // 0: pb.user_role.CreateUserRoleRequest
	(*UserRoleResponse)(nil),      // 1: pb.user_role.UserRoleResponse
	(*ApiResponseUserRole)(nil),   // 2: pb.user_role.ApiResponseUserRole
}
var file_user_role_user_role_proto_depIdxs = []int32{
	1, // 0: pb.user_role.ApiResponseUserRole.data:type_name -> pb.user_role.UserRoleResponse
	0, // 1: pb.user_role.UserRoleService.AssignRole:input_type -> pb.user_role.CreateUserRoleRequest
	0, // 2: pb.user_role.UserRoleService.UpdateRole:input_type -> pb.user_role.CreateUserRoleRequest
	2, // 3: pb.user_role.UserRoleService.AssignRole:output_type -> pb.user_role.ApiResponseUserRole
	2, // 4: pb.user_role.UserRoleService.UpdateRole:output_type -> pb.user_role.ApiResponseUserRole
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_role_user_role_proto_init() }
func file_user_role_user_role_proto_init() {
	if File_user_role_user_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_role_user_role_proto_rawDesc), len(file_user_role_user_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_role_user_role_proto_goTypes,
		DependencyIndexes: file_user_role_user_role_proto_depIdxs,
		MessageInfos:      file_user_role_user_role_proto_msgTypes,
	}.Build()
	File_user_role_user_role_proto = out.File
	file_user_role_user_role_proto_goTypes = nil
	file_user_role_user_role_proto_depIdxs = nil
}
