// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: role/command.proto

package role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_role_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_role_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateRoleRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ApiResponseRoleAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRoleAll) Reset() {
	*x = ApiResponseRoleAll{}
	mi := &file_role_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRoleAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRoleAll) ProtoMessage() {}

func (x *ApiResponseRoleAll) ProtoReflect() protoreflect.Message {
	mi := &file_role_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRoleAll.ProtoReflect.Descriptor instead.
func (*ApiResponseRoleAll) Descriptor() ([]byte, []int) {
	return file_role_command_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponseRoleAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRoleAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseRoleDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRoleDelete) Reset() {
	*x = ApiResponseRoleDelete{}
	mi := &file_role_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRoleDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRoleDelete) ProtoMessage() {}

func (x *ApiResponseRoleDelete) ProtoReflect() protoreflect.Message {
	mi := &file_role_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRoleDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseRoleDelete) Descriptor() ([]byte, []int) {
	return file_role_command_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseRoleDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRoleDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_role_command_proto protoreflect.FileDescriptor

const file_role_command_proto_rawDesc = "" +
	"\n" +
	"\x12role/command.proto\x12\apb.role\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11role/common.proto\"'\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"F\n" +
	"\x12ApiResponseRoleAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x15ApiResponseRoleDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xb3\x04\n" +
	"\x12RoleCommandService\x12D\n" +
	"\n" +
	"CreateRole\x12\x1a.pb.role.CreateRoleRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12D\n" +
	"\n" +
	"UpdateRole\x12\x1a.pb.role.UpdateRoleRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12O\n" +
	"\vTrashedRole\x12\x1c.pb.role.FindByIdRoleRequest\x1a .pb.role.ApiResponseRoleDeleteAt\"\x00\x12O\n" +
	"\vRestoreRole\x12\x1c.pb.role.FindByIdRoleRequest\x1a .pb.role.ApiResponseRoleDeleteAt\"\x00\x12U\n" +
	"\x13DeleteRolePermanent\x12\x1c.pb.role.FindByIdRoleRequest\x1a\x1e.pb.role.ApiResponseRoleDelete\"\x00\x12G\n" +
	"\x0eRestoreAllRole\x12\x16.google.protobuf.Empty\x1a\x1b.pb.role.ApiResponseRoleAll\"\x00\x12O\n" +
	"\x16DeleteAllRolePermanent\x12\x16.google.protobuf.Empty\x1a\x1b.pb.role.ApiResponseRoleAll\"\x00B=Z;github.com/MamangRust/simple_microservice_ecommerce_pb/roleb\x06proto3"

var (
	file_role_command_proto_rawDescOnce sync.Once
	file_role_command_proto_rawDescData []byte
)

func file_role_command_proto_rawDescGZIP() []byte {
	file_role_command_proto_rawDescOnce.Do(func() {
		file_role_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_command_proto_rawDesc), len(file_role_command_proto_rawDesc)))
	})
	return file_role_command_proto_rawDescData
}

var file_role_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_role_command_proto_goTypes = []any{
	(*CreateRoleRequest)(nil),       // 0: pb.role.CreateRoleRequest
	(*UpdateRoleRequest)(nil),       // 1: pb.role.UpdateRoleRequest
	(*ApiResponseRoleAll)(nil),      // 2: pb.role.ApiResponseRoleAll
	(*ApiResponseRoleDelete)(nil),   // 3: pb.role.ApiResponseRoleDelete
	(*FindByIdRoleRequest)(nil),     // 4: pb.role.FindByIdRoleRequest
	(*emptypb.Empty)(nil),           // 5: google.protobuf.Empty
	(*ApiResponseRole)(nil),         // 6: pb.role.ApiResponseRole
	(*ApiResponseRoleDeleteAt)(nil), // 7: pb.role.ApiResponseRoleDeleteAt
}
var file_role_command_proto_depIdxs = []int32{
	0, // 0: pb.role.RoleCommandService.CreateRole:input_type -> pb.role.CreateRoleRequest
	1, // 1: pb.role.RoleCommandService.UpdateRole:input_type -> pb.role.UpdateRoleRequest
	4, // 2: pb.role.RoleCommandService.TrashedRole:input_type -> pb.role.FindByIdRoleRequest
	4, // 3: pb.role.RoleCommandService.RestoreRole:input_type -> pb.role.FindByIdRoleRequest
	4, // 4: pb.role.RoleCommandService.DeleteRolePermanent:input_type -> pb.role.FindByIdRoleRequest
	5, // 5: pb.role.RoleCommandService.RestoreAllRole:input_type -> google.protobuf.Empty
	5, // 6: pb.role.RoleCommandService.DeleteAllRolePermanent:input_type -> google.protobuf.Empty
	6, // 7: pb.role.RoleCommandService.CreateRole:output_type -> pb.role.ApiResponseRole
	6, // 8: pb.role.RoleCommandService.UpdateRole:output_type -> pb.role.ApiResponseRole
	7, // 9: pb.role.RoleCommandService.TrashedRole:output_type -> pb.role.ApiResponseRoleDeleteAt
	7, // 10: pb.role.RoleCommandService.RestoreRole:output_type -> pb.role.ApiResponseRoleDeleteAt
	3, // 11: pb.role.RoleCommandService.DeleteRolePermanent:output_type -> pb.role.ApiResponseRoleDelete
	2, // 12: pb.role.RoleCommandService.RestoreAllRole:output_type -> pb.role.ApiResponseRoleAll
	2, // 13: pb.role.RoleCommandService.DeleteAllRolePermanent:output_type -> pb.role.ApiResponseRoleAll
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_role_command_proto_init() }
func file_role_command_proto_init() {
	if File_role_command_proto != nil {
		return
	}
	file_role_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_command_proto_rawDesc), len(file_role_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_command_proto_goTypes,
		DependencyIndexes: file_role_command_proto_depIdxs,
		MessageInfos:      file_role_command_proto_msgTypes,
	}.Build()
	File_role_command_proto = out.File
	file_role_command_proto_goTypes = nil
	file_role_command_proto_depIdxs = nil
}
