// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: role/common.proto

package role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllRoleRequest) Reset() {
	*x = FindAllRoleRequest{}
	mi := &file_role_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllRoleRequest) ProtoMessage() {}

func (x *FindAllRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllRoleRequest.ProtoReflect.Descriptor instead.
func (*FindAllRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_common_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllRoleRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllRoleRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllRoleRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int32                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdRoleRequest) Reset() {
	*x = FindByIdRoleRequest{}
	mi := &file_role_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRoleRequest) ProtoMessage() {}

func (x *FindByIdRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRoleRequest.ProtoReflect.Descriptor instead.
func (*FindByIdRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_common_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdRoleRequest) GetRoleId() int32 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type FindByIdUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdUserRoleRequest) Reset() {
	*x = FindByIdUserRoleRequest{}
	mi := &file_role_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdUserRoleRequest) ProtoMessage() {}

func (x *FindByIdUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdUserRoleRequest.ProtoReflect.Descriptor instead.
func (*FindByIdUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_common_proto_rawDescGZIP(), []int{2}
}

func (x *FindByIdUserRoleRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_role_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_role_common_proto_rawDescGZIP(), []int{3}
}

func (x *RoleResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RoleResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponseDeleteAt) Reset() {
	*x = RoleResponseDeleteAt{}
	mi := &file_role_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponseDeleteAt) ProtoMessage() {}

func (x *RoleResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_role_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*RoleResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_role_common_proto_rawDescGZIP(), []int{4}
}

func (x *RoleResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RoleResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RoleResponse          `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRole) Reset() {
	*x = ApiResponseRole{}
	mi := &file_role_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRole) ProtoMessage() {}

func (x *ApiResponseRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRole.ProtoReflect.Descriptor instead.
func (*ApiResponseRole) Descriptor() ([]byte, []int) {
	return file_role_common_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseRole) GetData() *RoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseRoleDeleteAt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *RoleResponseDeleteAt  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseRoleDeleteAt) Reset() {
	*x = ApiResponseRoleDeleteAt{}
	mi := &file_role_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseRoleDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseRoleDeleteAt) ProtoMessage() {}

func (x *ApiResponseRoleDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_role_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseRoleDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseRoleDeleteAt) Descriptor() ([]byte, []int) {
	return file_role_common_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseRoleDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseRoleDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseRoleDeleteAt) GetData() *RoleResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*RoleResponse        `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesRole) Reset() {
	*x = ApiResponsesRole{}
	mi := &file_role_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesRole) ProtoMessage() {}

func (x *ApiResponsesRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesRole.ProtoReflect.Descriptor instead.
func (*ApiResponsesRole) Descriptor() ([]byte, []int) {
	return file_role_common_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponsesRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesRole) GetData() []*RoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_role_common_proto protoreflect.FileDescriptor

const file_role_common_proto_rawDesc = "" +
	"\n" +
	"\x11role/common.proto\x12\apb.role\x1a\x1egoogle/protobuf/wrappers.proto\"]\n" +
	"\x12FindAllRoleRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\".\n" +
	"\x13FindByIdRoleRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x05R\x06roleId\"2\n" +
	"\x17FindByIdUserRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"p\n" +
	"\fRoleResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\"\xb5\x01\n" +
	"\x14RoleResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"n\n" +
	"\x0fApiResponseRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x01(\v2\x15.pb.role.RoleResponseR\x04data\"~\n" +
	"\x17ApiResponseRoleDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x01(\v2\x1d.pb.role.RoleResponseDeleteAtR\x04data\"o\n" +
	"\x10ApiResponsesRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.role.RoleResponseR\x04dataB=Z;github.com/MamangRust/simple_microservice_ecommerce_pb/roleb\x06proto3"

var (
	file_role_common_proto_rawDescOnce sync.Once
	file_role_common_proto_rawDescData []byte
)

func file_role_common_proto_rawDescGZIP() []byte {
	file_role_common_proto_rawDescOnce.Do(func() {
		file_role_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_common_proto_rawDesc), len(file_role_common_proto_rawDesc)))
	})
	return file_role_common_proto_rawDescData
}

var file_role_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_role_common_proto_goTypes = []any{
	(*FindAllRoleRequest)(nil),      // 0: pb.role.FindAllRoleRequest
	(*FindByIdRoleRequest)(nil),     // 1: pb.role.FindByIdRoleRequest
	(*FindByIdUserRoleRequest)(nil), // 2: pb.role.FindByIdUserRoleRequest
	(*RoleResponse)(nil),            // 3: pb.role.RoleResponse
	(*RoleResponseDeleteAt)(nil),    // 4: pb.role.RoleResponseDeleteAt
	(*ApiResponseRole)(nil),         // 5: pb.role.ApiResponseRole
	(*ApiResponseRoleDeleteAt)(nil), // 6: pb.role.ApiResponseRoleDeleteAt
	(*ApiResponsesRole)(nil),        // 7: pb.role.ApiResponsesRole
	(*wrapperspb.StringValue)(nil),  // 8: google.protobuf.StringValue
}
var file_role_common_proto_depIdxs = []int32{
	8, // 0: pb.role.RoleResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	3, // 1: pb.role.ApiResponseRole.data:type_name -> pb.role.RoleResponse
	4, // 2: pb.role.ApiResponseRoleDeleteAt.data:type_name -> pb.role.RoleResponseDeleteAt
	3, // 3: pb.role.ApiResponsesRole.data:type_name -> pb.role.RoleResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_role_common_proto_init() }
func file_role_common_proto_init() {
	if File_role_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_common_proto_rawDesc), len(file_role_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_common_proto_goTypes,
		DependencyIndexes: file_role_common_proto_depIdxs,
		MessageInfos:      file_role_common_proto_msgTypes,
	}.Build()
	File_role_common_proto = out.File
	file_role_common_proto_goTypes = nil
	file_role_common_proto_depIdxs = nil
}
