// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: role/query.proto

package role

import (
	simple_microservice_ecommerce_pb "github.com/MamangRust/simple_microservice_ecommerce_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          int32                  `protobuf:"varint,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByNameRequest) Reset() {
	*x = FindByNameRequest{}
	mi := &file_role_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByNameRequest) ProtoMessage() {}

func (x *FindByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByNameRequest.ProtoReflect.Descriptor instead.
func (*FindByNameRequest) Descriptor() ([]byte, []int) {
	return file_role_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindByNameRequest) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

type ApiResponsePaginationRole struct {
	state          protoimpl.MessageState                       `protogen:"open.v1"`
	Status         string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*RoleResponse                              `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationRole) Reset() {
	*x = ApiResponsePaginationRole{}
	mi := &file_role_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationRole) ProtoMessage() {}

func (x *ApiResponsePaginationRole) ProtoReflect() protoreflect.Message {
	mi := &file_role_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationRole.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationRole) Descriptor() ([]byte, []int) {
	return file_role_query_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponsePaginationRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationRole) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationRole) GetData() []*RoleResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationRole) GetPaginationMeta() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

type ApiResponsePaginationRoleDeleteAt struct {
	state          protoimpl.MessageState                       `protogen:"open.v1"`
	Status         string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data           []*RoleResponseDeleteAt                      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	PaginationMeta *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=paginationMeta,proto3" json:"paginationMeta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApiResponsePaginationRoleDeleteAt) Reset() {
	*x = ApiResponsePaginationRoleDeleteAt{}
	mi := &file_role_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationRoleDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationRoleDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationRoleDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_role_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationRoleDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationRoleDeleteAt) Descriptor() ([]byte, []int) {
	return file_role_query_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponsePaginationRoleDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationRoleDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationRoleDeleteAt) GetData() []*RoleResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationRoleDeleteAt) GetPaginationMeta() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.PaginationMeta
	}
	return nil
}

var File_role_query_proto protoreflect.FileDescriptor

const file_role_query_proto_rawDesc = "" +
	"\n" +
	"\x10role/query.proto\x12\apb.role\x1a\tapi.proto\x1a\x11role/common.proto\"'\n" +
	"\x11FindByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\x05R\x04name\"\xb0\x01\n" +
	"\x19ApiResponsePaginationRole\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.role.RoleResponseR\x04data\x126\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x0e.pb.PaginationR\x0epaginationMeta\"\xc0\x01\n" +
	"!ApiResponsePaginationRoleDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.role.RoleResponseDeleteAtR\x04data\x126\n" +
	"\x0epaginationMeta\x18\x04 \x01(\v2\x0e.pb.PaginationR\x0epaginationMeta2\xfa\x03\n" +
	"\x10RoleQueryService\x12P\n" +
	"\vFindAllRole\x12\x1b.pb.role.FindAllRoleRequest\x1a\".pb.role.ApiResponsePaginationRole\"\x00\x12D\n" +
	"\n" +
	"FindByName\x12\x1a.pb.role.FindByNameRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12H\n" +
	"\fFindByIdRole\x12\x1c.pb.role.FindByIdRoleRequest\x1a\x18.pb.role.ApiResponseRole\"\x00\x12Y\n" +
	"\fFindByActive\x12\x1b.pb.role.FindAllRoleRequest\x1a*.pb.role.ApiResponsePaginationRoleDeleteAt\"\x00\x12Z\n" +
	"\rFindByTrashed\x12\x1b.pb.role.FindAllRoleRequest\x1a*.pb.role.ApiResponsePaginationRoleDeleteAt\"\x00\x12M\n" +
	"\fFindByUserId\x12 .pb.role.FindByIdUserRoleRequest\x1a\x19.pb.role.ApiResponsesRole\"\x00B=Z;github.com/MamangRust/simple_microservice_ecommerce_pb/roleb\x06proto3"

var (
	file_role_query_proto_rawDescOnce sync.Once
	file_role_query_proto_rawDescData []byte
)

func file_role_query_proto_rawDescGZIP() []byte {
	file_role_query_proto_rawDescOnce.Do(func() {
		file_role_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_query_proto_rawDesc), len(file_role_query_proto_rawDesc)))
	})
	return file_role_query_proto_rawDescData
}

var file_role_query_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_role_query_proto_goTypes = []any{
	(*FindByNameRequest)(nil),                           // 0: pb.role.FindByNameRequest
	(*ApiResponsePaginationRole)(nil),                   // 1: pb.role.ApiResponsePaginationRole
	(*ApiResponsePaginationRoleDeleteAt)(nil),           // 2: pb.role.ApiResponsePaginationRoleDeleteAt
	(*RoleResponse)(nil),                                // 3: pb.role.RoleResponse
	(*simple_microservice_ecommerce_pb.Pagination)(nil), // 4: pb.Pagination
	(*RoleResponseDeleteAt)(nil),                        // 5: pb.role.RoleResponseDeleteAt
	(*FindAllRoleRequest)(nil),                          // 6: pb.role.FindAllRoleRequest
	(*FindByIdRoleRequest)(nil),                         // 7: pb.role.FindByIdRoleRequest
	(*FindByIdUserRoleRequest)(nil),                     // 8: pb.role.FindByIdUserRoleRequest
	(*ApiResponseRole)(nil),                             // 9: pb.role.ApiResponseRole
	(*ApiResponsesRole)(nil),                            // 10: pb.role.ApiResponsesRole
}
var file_role_query_proto_depIdxs = []int32{
	3,  // 0: pb.role.ApiResponsePaginationRole.data:type_name -> pb.role.RoleResponse
	4,  // 1: pb.role.ApiResponsePaginationRole.paginationMeta:type_name -> pb.Pagination
	5,  // 2: pb.role.ApiResponsePaginationRoleDeleteAt.data:type_name -> pb.role.RoleResponseDeleteAt
	4,  // 3: pb.role.ApiResponsePaginationRoleDeleteAt.paginationMeta:type_name -> pb.Pagination
	6,  // 4: pb.role.RoleQueryService.FindAllRole:input_type -> pb.role.FindAllRoleRequest
	0,  // 5: pb.role.RoleQueryService.FindByName:input_type -> pb.role.FindByNameRequest
	7,  // 6: pb.role.RoleQueryService.FindByIdRole:input_type -> pb.role.FindByIdRoleRequest
	6,  // 7: pb.role.RoleQueryService.FindByActive:input_type -> pb.role.FindAllRoleRequest
	6,  // 8: pb.role.RoleQueryService.FindByTrashed:input_type -> pb.role.FindAllRoleRequest
	8,  // 9: pb.role.RoleQueryService.FindByUserId:input_type -> pb.role.FindByIdUserRoleRequest
	1,  // 10: pb.role.RoleQueryService.FindAllRole:output_type -> pb.role.ApiResponsePaginationRole
	9,  // 11: pb.role.RoleQueryService.FindByName:output_type -> pb.role.ApiResponseRole
	9,  // 12: pb.role.RoleQueryService.FindByIdRole:output_type -> pb.role.ApiResponseRole
	2,  // 13: pb.role.RoleQueryService.FindByActive:output_type -> pb.role.ApiResponsePaginationRoleDeleteAt
	2,  // 14: pb.role.RoleQueryService.FindByTrashed:output_type -> pb.role.ApiResponsePaginationRoleDeleteAt
	10, // 15: pb.role.RoleQueryService.FindByUserId:output_type -> pb.role.ApiResponsesRole
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_role_query_proto_init() }
func file_role_query_proto_init() {
	if File_role_query_proto != nil {
		return
	}
	file_role_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_query_proto_rawDesc), len(file_role_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_query_proto_goTypes,
		DependencyIndexes: file_role_query_proto_depIdxs,
		MessageInfos:      file_role_query_proto_msgTypes,
	}.Build()
	File_role_query_proto = out.File
	file_role_query_proto_goTypes = nil
	file_role_query_proto_depIdxs = nil
}
