// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: order_item/orderitem.proto

package order_item

import (
	simple_microservice_ecommerce_pb "github.com/MamangRust/simple_microservice_ecommerce_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllOrderItemRequest) Reset() {
	*x = FindAllOrderItemRequest{}
	mi := &file_order_item_orderitem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllOrderItemRequest) ProtoMessage() {}

func (x *FindAllOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllOrderItemRequest.ProtoReflect.Descriptor instead.
func (*FindAllOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllOrderItemRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllOrderItemRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllOrderItemRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdOrderItemRequest) Reset() {
	*x = FindByIdOrderItemRequest{}
	mi := &file_order_item_orderitem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdOrderItemRequest) ProtoMessage() {}

func (x *FindByIdOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdOrderItemRequest.ProtoReflect.Descriptor instead.
func (*FindByIdOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{1}
}

func (x *FindByIdOrderItemRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type OrderItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int32                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemResponse) Reset() {
	*x = OrderItemResponse{}
	mi := &file_order_item_orderitem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemResponse) ProtoMessage() {}

func (x *OrderItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemResponse.ProtoReflect.Descriptor instead.
func (*OrderItemResponse) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{2}
}

func (x *OrderItemResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItemResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItemResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItemResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemResponse) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItemResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderItemResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type OrderItemResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                   `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     int32                   `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                   `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemResponseDeleteAt) Reset() {
	*x = OrderItemResponseDeleteAt{}
	mi := &file_order_item_orderitem_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemResponseDeleteAt) ProtoMessage() {}

func (x *OrderItemResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*OrderItemResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{3}
}

func (x *OrderItemResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItemResponseDeleteAt) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItemResponseDeleteAt) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItemResponseDeleteAt) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemResponseDeleteAt) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderItemResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OrderItemResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *OrderItemResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *OrderItemResponse     `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderItem) Reset() {
	*x = ApiResponseOrderItem{}
	mi := &file_order_item_orderitem_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderItem) ProtoMessage() {}

func (x *ApiResponseOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderItem.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderItem) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseOrderItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseOrderItem) GetData() *OrderItemResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponsesOrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderItemResponse   `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsesOrderItem) Reset() {
	*x = ApiResponsesOrderItem{}
	mi := &file_order_item_orderitem_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsesOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsesOrderItem) ProtoMessage() {}

func (x *ApiResponsesOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsesOrderItem.ProtoReflect.Descriptor instead.
func (*ApiResponsesOrderItem) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponsesOrderItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsesOrderItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsesOrderItem) GetData() []*OrderItemResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseOrderItemDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderItemDelete) Reset() {
	*x = ApiResponseOrderItemDelete{}
	mi := &file_order_item_orderitem_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderItemDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderItemDelete) ProtoMessage() {}

func (x *ApiResponseOrderItemDelete) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderItemDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderItemDelete) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{6}
}

func (x *ApiResponseOrderItemDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderItemDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseOrderItemAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseOrderItemAll) Reset() {
	*x = ApiResponseOrderItemAll{}
	mi := &file_order_item_orderitem_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseOrderItemAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseOrderItemAll) ProtoMessage() {}

func (x *ApiResponseOrderItemAll) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseOrderItemAll.ProtoReflect.Descriptor instead.
func (*ApiResponseOrderItemAll) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{7}
}

func (x *ApiResponseOrderItemAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseOrderItemAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationOrderItemDeleteAt struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Status        string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderItemResponseDeleteAt                 `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationOrderItemDeleteAt) Reset() {
	*x = ApiResponsePaginationOrderItemDeleteAt{}
	mi := &file_order_item_orderitem_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationOrderItemDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationOrderItemDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationOrderItemDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationOrderItemDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationOrderItemDeleteAt) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{8}
}

func (x *ApiResponsePaginationOrderItemDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationOrderItemDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationOrderItemDeleteAt) GetData() []*OrderItemResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationOrderItemDeleteAt) GetPagination() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationOrderItem struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Status        string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*OrderItemResponse                         `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationOrderItem) Reset() {
	*x = ApiResponsePaginationOrderItem{}
	mi := &file_order_item_orderitem_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationOrderItem) ProtoMessage() {}

func (x *ApiResponsePaginationOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_item_orderitem_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationOrderItem.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationOrderItem) Descriptor() ([]byte, []int) {
	return file_order_item_orderitem_proto_rawDescGZIP(), []int{9}
}

func (x *ApiResponsePaginationOrderItem) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationOrderItem) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationOrderItem) GetData() []*OrderItemResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationOrderItem) GetPagination() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_order_item_orderitem_proto protoreflect.FileDescriptor

const file_order_item_orderitem_proto_rawDesc = "" +
	"\n" +
	"\x1aorder_item/orderitem.proto\x12\rpb.order_item\x1a\x1egoogle/protobuf/wrappers.proto\x1a\tapi.proto\"b\n" +
	"\x17FindAllOrderItemRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"*\n" +
	"\x18FindByIdOrderItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xcd\x01\n" +
	"\x11OrderItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"\x92\x02\n" +
	"\x19OrderItemResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"~\n" +
	"\x14ApiResponseOrderItem\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x04data\x18\x03 \x01(\v2 .pb.order_item.OrderItemResponseR\x04data\"\x7f\n" +
	"\x15ApiResponsesOrderItem\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x04data\x18\x03 \x03(\v2 .pb.order_item.OrderItemResponseR\x04data\"N\n" +
	"\x1aApiResponseOrderItemDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x17ApiResponseOrderItemAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc8\x01\n" +
	"&ApiResponsePaginationOrderItemDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.pb.order_item.OrderItemResponseDeleteAtR\x04data\x12.\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination\"\xb8\x01\n" +
	"\x1eApiResponsePaginationOrderItem\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\x04data\x18\x03 \x03(\v2 .pb.order_item.OrderItemResponseR\x04data\x12.\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination2\xba\x03\n" +
	"\x10OrderItemService\x12`\n" +
	"\aFindAll\x12&.pb.order_item.FindAllOrderItemRequest\x1a-.pb.order_item.ApiResponsePaginationOrderItem\x12m\n" +
	"\fFindByActive\x12&.pb.order_item.FindAllOrderItemRequest\x1a5.pb.order_item.ApiResponsePaginationOrderItemDeleteAt\x12n\n" +
	"\rFindByTrashed\x12&.pb.order_item.FindAllOrderItemRequest\x1a5.pb.order_item.ApiResponsePaginationOrderItemDeleteAt\x12e\n" +
	"\x14FindOrderItemByOrder\x12'.pb.order_item.FindByIdOrderItemRequest\x1a$.pb.order_item.ApiResponsesOrderItemBCZAgithub.com/MamangRust/simple_microservice_ecommerce_pb/order_itemb\x06proto3"

var (
	file_order_item_orderitem_proto_rawDescOnce sync.Once
	file_order_item_orderitem_proto_rawDescData []byte
)

func file_order_item_orderitem_proto_rawDescGZIP() []byte {
	file_order_item_orderitem_proto_rawDescOnce.Do(func() {
		file_order_item_orderitem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_item_orderitem_proto_rawDesc), len(file_order_item_orderitem_proto_rawDesc)))
	})
	return file_order_item_orderitem_proto_rawDescData
}

var file_order_item_orderitem_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_order_item_orderitem_proto_goTypes = []any{
	(*FindAllOrderItemRequest)(nil),                     // 0: pb.order_item.FindAllOrderItemRequest
	(*FindByIdOrderItemRequest)(nil),                    // 1: pb.order_item.FindByIdOrderItemRequest
	(*OrderItemResponse)(nil),                           // 2: pb.order_item.OrderItemResponse
	(*OrderItemResponseDeleteAt)(nil),                   // 3: pb.order_item.OrderItemResponseDeleteAt
	(*ApiResponseOrderItem)(nil),                        // 4: pb.order_item.ApiResponseOrderItem
	(*ApiResponsesOrderItem)(nil),                       // 5: pb.order_item.ApiResponsesOrderItem
	(*ApiResponseOrderItemDelete)(nil),                  // 6: pb.order_item.ApiResponseOrderItemDelete
	(*ApiResponseOrderItemAll)(nil),                     // 7: pb.order_item.ApiResponseOrderItemAll
	(*ApiResponsePaginationOrderItemDeleteAt)(nil),      // 8: pb.order_item.ApiResponsePaginationOrderItemDeleteAt
	(*ApiResponsePaginationOrderItem)(nil),              // 9: pb.order_item.ApiResponsePaginationOrderItem
	(*wrapperspb.StringValue)(nil),                      // 10: google.protobuf.StringValue
	(*simple_microservice_ecommerce_pb.Pagination)(nil), // 11: pb.Pagination
}
var file_order_item_orderitem_proto_depIdxs = []int32{
	10, // 0: pb.order_item.OrderItemResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	2,  // 1: pb.order_item.ApiResponseOrderItem.data:type_name -> pb.order_item.OrderItemResponse
	2,  // 2: pb.order_item.ApiResponsesOrderItem.data:type_name -> pb.order_item.OrderItemResponse
	3,  // 3: pb.order_item.ApiResponsePaginationOrderItemDeleteAt.data:type_name -> pb.order_item.OrderItemResponseDeleteAt
	11, // 4: pb.order_item.ApiResponsePaginationOrderItemDeleteAt.pagination:type_name -> pb.Pagination
	2,  // 5: pb.order_item.ApiResponsePaginationOrderItem.data:type_name -> pb.order_item.OrderItemResponse
	11, // 6: pb.order_item.ApiResponsePaginationOrderItem.pagination:type_name -> pb.Pagination
	0,  // 7: pb.order_item.OrderItemService.FindAll:input_type -> pb.order_item.FindAllOrderItemRequest
	0,  // 8: pb.order_item.OrderItemService.FindByActive:input_type -> pb.order_item.FindAllOrderItemRequest
	0,  // 9: pb.order_item.OrderItemService.FindByTrashed:input_type -> pb.order_item.FindAllOrderItemRequest
	1,  // 10: pb.order_item.OrderItemService.FindOrderItemByOrder:input_type -> pb.order_item.FindByIdOrderItemRequest
	9,  // 11: pb.order_item.OrderItemService.FindAll:output_type -> pb.order_item.ApiResponsePaginationOrderItem
	8,  // 12: pb.order_item.OrderItemService.FindByActive:output_type -> pb.order_item.ApiResponsePaginationOrderItemDeleteAt
	8,  // 13: pb.order_item.OrderItemService.FindByTrashed:output_type -> pb.order_item.ApiResponsePaginationOrderItemDeleteAt
	5,  // 14: pb.order_item.OrderItemService.FindOrderItemByOrder:output_type -> pb.order_item.ApiResponsesOrderItem
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_order_item_orderitem_proto_init() }
func file_order_item_orderitem_proto_init() {
	if File_order_item_orderitem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_item_orderitem_proto_rawDesc), len(file_order_item_orderitem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_item_orderitem_proto_goTypes,
		DependencyIndexes: file_order_item_orderitem_proto_depIdxs,
		MessageInfos:      file_order_item_orderitem_proto_msgTypes,
	}.Build()
	File_order_item_orderitem_proto = out.File
	file_order_item_orderitem_proto_goTypes = nil
	file_order_item_orderitem_proto_depIdxs = nil
}
