// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: product/command.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type UpdateProductStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductStockRequest) Reset() {
	*x = UpdateProductStockRequest{}
	mi := &file_product_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductStockRequest) ProtoMessage() {}

func (x *UpdateProductStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductStockRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductStockRequest) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateProductStockRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductStockRequest) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type ApiResponseProductDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseProductDelete) Reset() {
	*x = ApiResponseProductDelete{}
	mi := &file_product_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseProductDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseProductDelete) ProtoMessage() {}

func (x *ApiResponseProductDelete) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseProductDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseProductDelete) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseProductDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseProductDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseProductAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseProductAll) Reset() {
	*x = ApiResponseProductAll{}
	mi := &file_product_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseProductAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseProductAll) ProtoMessage() {}

func (x *ApiResponseProductAll) ProtoReflect() protoreflect.Message {
	mi := &file_product_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseProductAll.ProtoReflect.Descriptor instead.
func (*ApiResponseProductAll) Descriptor() ([]byte, []int) {
	return file_product_command_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseProductAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseProductAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_product_command_proto protoreflect.FileDescriptor

const file_product_command_proto_rawDesc = "" +
	"\n" +
	"\x15product/command.proto\x12\n" +
	"pb.product\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14product/common.proto\"V\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x05R\x05stock\"f\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\"A\n" +
	"\x19UpdateProductStockRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock\"L\n" +
	"\x18ApiResponseProductDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x15ApiResponseProductAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc2\x05\n" +
	"\x15ProductCommandService\x12J\n" +
	"\x06Create\x12 .pb.product.CreateProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12J\n" +
	"\x06Update\x12 .pb.product.UpdateProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12`\n" +
	"\x17UpdateProductCountStock\x12%.pb.product.UpdateProductStockRequest\x1a\x1e.pb.product.ApiResponseProduct\x12U\n" +
	"\aTrashed\x12\".pb.product.FindByIdProductRequest\x1a&.pb.product.ApiResponseProductDeleteAt\x12U\n" +
	"\aRestore\x12\".pb.product.FindByIdProductRequest\x1a&.pb.product.ApiResponseProductDeleteAt\x12b\n" +
	"\x16DeleteProductPermanent\x12\".pb.product.FindByIdProductRequest\x1a$.pb.product.ApiResponseProductDelete\x12N\n" +
	"\x11RestoreAllProduct\x12\x16.google.protobuf.Empty\x1a!.pb.product.ApiResponseProductAll\x12M\n" +
	"\x10DeleteAllProduct\x12\x16.google.protobuf.Empty\x1a!.pb.product.ApiResponseProductAllB@Z>github.com/MamangRust/simple_microservice_ecommerce_pb/productb\x06proto3"

var (
	file_product_command_proto_rawDescOnce sync.Once
	file_product_command_proto_rawDescData []byte
)

func file_product_command_proto_rawDescGZIP() []byte {
	file_product_command_proto_rawDescOnce.Do(func() {
		file_product_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_command_proto_rawDesc), len(file_product_command_proto_rawDesc)))
	})
	return file_product_command_proto_rawDescData
}

var file_product_command_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_product_command_proto_goTypes = []any{
	(*CreateProductRequest)(nil),       // 0: pb.product.CreateProductRequest
	(*UpdateProductRequest)(nil),       // 1: pb.product.UpdateProductRequest
	(*UpdateProductStockRequest)(nil),  // 2: pb.product.UpdateProductStockRequest
	(*ApiResponseProductDelete)(nil),   // 3: pb.product.ApiResponseProductDelete
	(*ApiResponseProductAll)(nil),      // 4: pb.product.ApiResponseProductAll
	(*FindByIdProductRequest)(nil),     // 5: pb.product.FindByIdProductRequest
	(*emptypb.Empty)(nil),              // 6: google.protobuf.Empty
	(*ApiResponseProduct)(nil),         // 7: pb.product.ApiResponseProduct
	(*ApiResponseProductDeleteAt)(nil), // 8: pb.product.ApiResponseProductDeleteAt
}
var file_product_command_proto_depIdxs = []int32{
	0, // 0: pb.product.ProductCommandService.Create:input_type -> pb.product.CreateProductRequest
	1, // 1: pb.product.ProductCommandService.Update:input_type -> pb.product.UpdateProductRequest
	2, // 2: pb.product.ProductCommandService.UpdateProductCountStock:input_type -> pb.product.UpdateProductStockRequest
	5, // 3: pb.product.ProductCommandService.Trashed:input_type -> pb.product.FindByIdProductRequest
	5, // 4: pb.product.ProductCommandService.Restore:input_type -> pb.product.FindByIdProductRequest
	5, // 5: pb.product.ProductCommandService.DeleteProductPermanent:input_type -> pb.product.FindByIdProductRequest
	6, // 6: pb.product.ProductCommandService.RestoreAllProduct:input_type -> google.protobuf.Empty
	6, // 7: pb.product.ProductCommandService.DeleteAllProduct:input_type -> google.protobuf.Empty
	7, // 8: pb.product.ProductCommandService.Create:output_type -> pb.product.ApiResponseProduct
	7, // 9: pb.product.ProductCommandService.Update:output_type -> pb.product.ApiResponseProduct
	7, // 10: pb.product.ProductCommandService.UpdateProductCountStock:output_type -> pb.product.ApiResponseProduct
	8, // 11: pb.product.ProductCommandService.Trashed:output_type -> pb.product.ApiResponseProductDeleteAt
	8, // 12: pb.product.ProductCommandService.Restore:output_type -> pb.product.ApiResponseProductDeleteAt
	3, // 13: pb.product.ProductCommandService.DeleteProductPermanent:output_type -> pb.product.ApiResponseProductDelete
	4, // 14: pb.product.ProductCommandService.RestoreAllProduct:output_type -> pb.product.ApiResponseProductAll
	4, // 15: pb.product.ProductCommandService.DeleteAllProduct:output_type -> pb.product.ApiResponseProductAll
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_command_proto_init() }
func file_product_command_proto_init() {
	if File_product_command_proto != nil {
		return
	}
	file_product_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_command_proto_rawDesc), len(file_product_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_command_proto_goTypes,
		DependencyIndexes: file_product_command_proto_depIdxs,
		MessageInfos:      file_product_command_proto_msgTypes,
	}.Build()
	File_product_command_proto = out.File
	file_product_command_proto_goTypes = nil
	file_product_command_proto_depIdxs = nil
}
