// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: product/common.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByIdProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdProductRequest) Reset() {
	*x = FindByIdProductRequest{}
	mi := &file_product_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdProductRequest) ProtoMessage() {}

func (x *FindByIdProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdProductRequest.ProtoReflect.Descriptor instead.
func (*FindByIdProductRequest) Descriptor() ([]byte, []int) {
	return file_product_common_proto_rawDescGZIP(), []int{0}
}

func (x *FindByIdProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_common_proto_rawDescGZIP(), []int{1}
}

func (x *ProductResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ProductResponseDeleteAt struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                   `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	CreatedAt     string                  `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                  `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponseDeleteAt) Reset() {
	*x = ProductResponseDeleteAt{}
	mi := &file_product_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponseDeleteAt) ProtoMessage() {}

func (x *ProductResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_product_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*ProductResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_product_common_proto_rawDescGZIP(), []int{2}
}

func (x *ProductResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ProductResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ApiResponseProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ProductResponse       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseProduct) Reset() {
	*x = ApiResponseProduct{}
	mi := &file_product_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseProduct) ProtoMessage() {}

func (x *ApiResponseProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseProduct.ProtoReflect.Descriptor instead.
func (*ApiResponseProduct) Descriptor() ([]byte, []int) {
	return file_product_common_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponseProduct) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseProduct) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseProduct) GetData() *ProductResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseProductDeleteAt struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Status        string                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *ProductResponseDeleteAt `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseProductDeleteAt) Reset() {
	*x = ApiResponseProductDeleteAt{}
	mi := &file_product_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseProductDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseProductDeleteAt) ProtoMessage() {}

func (x *ApiResponseProductDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_product_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseProductDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponseProductDeleteAt) Descriptor() ([]byte, []int) {
	return file_product_common_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseProductDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseProductDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseProductDeleteAt) GetData() *ProductResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_product_common_proto protoreflect.FileDescriptor

const file_product_common_proto_rawDesc = "" +
	"\n" +
	"\x14product/common.proto\x12\n" +
	"pb.product\x1a\x1egoogle/protobuf/wrappers.proto\"(\n" +
	"\x16FindByIdProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x9f\x01\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xe4\x01\n" +
	"\x17ProductResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"w\n" +
	"\x12ApiResponseProduct\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x01(\v2\x1b.pb.product.ProductResponseR\x04data\"\x87\x01\n" +
	"\x1aApiResponseProductDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x01(\v2#.pb.product.ProductResponseDeleteAtR\x04dataB@Z>github.com/MamangRust/simple_microservice_ecommerce_pb/productb\x06proto3"

var (
	file_product_common_proto_rawDescOnce sync.Once
	file_product_common_proto_rawDescData []byte
)

func file_product_common_proto_rawDescGZIP() []byte {
	file_product_common_proto_rawDescOnce.Do(func() {
		file_product_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_common_proto_rawDesc), len(file_product_common_proto_rawDesc)))
	})
	return file_product_common_proto_rawDescData
}

var file_product_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_product_common_proto_goTypes = []any{
	(*FindByIdProductRequest)(nil),     // 0: pb.product.FindByIdProductRequest
	(*ProductResponse)(nil),            // 1: pb.product.ProductResponse
	(*ProductResponseDeleteAt)(nil),    // 2: pb.product.ProductResponseDeleteAt
	(*ApiResponseProduct)(nil),         // 3: pb.product.ApiResponseProduct
	(*ApiResponseProductDeleteAt)(nil), // 4: pb.product.ApiResponseProductDeleteAt
	(*wrapperspb.StringValue)(nil),     // 5: google.protobuf.StringValue
}
var file_product_common_proto_depIdxs = []int32{
	5, // 0: pb.product.ProductResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	1, // 1: pb.product.ApiResponseProduct.data:type_name -> pb.product.ProductResponse
	2, // 2: pb.product.ApiResponseProductDeleteAt.data:type_name -> pb.product.ProductResponseDeleteAt
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_product_common_proto_init() }
func file_product_common_proto_init() {
	if File_product_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_common_proto_rawDesc), len(file_product_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_common_proto_goTypes,
		DependencyIndexes: file_product_common_proto_depIdxs,
		MessageInfos:      file_product_common_proto_msgTypes,
	}.Build()
	File_product_common_proto = out.File
	file_product_common_proto_goTypes = nil
	file_product_common_proto_depIdxs = nil
}
