// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: product/command.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductCommandService_Create_FullMethodName                  = "/pb.product.ProductCommandService/Create"
	ProductCommandService_Update_FullMethodName                  = "/pb.product.ProductCommandService/Update"
	ProductCommandService_UpdateProductCountStock_FullMethodName = "/pb.product.ProductCommandService/UpdateProductCountStock"
	ProductCommandService_Trashed_FullMethodName                 = "/pb.product.ProductCommandService/Trashed"
	ProductCommandService_Restore_FullMethodName                 = "/pb.product.ProductCommandService/Restore"
	ProductCommandService_DeleteProductPermanent_FullMethodName  = "/pb.product.ProductCommandService/DeleteProductPermanent"
	ProductCommandService_RestoreAllProduct_FullMethodName       = "/pb.product.ProductCommandService/RestoreAllProduct"
	ProductCommandService_DeleteAllProduct_FullMethodName        = "/pb.product.ProductCommandService/DeleteAllProduct"
)

// ProductCommandServiceClient is the client API for ProductCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductCommandServiceClient interface {
	Create(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error)
	Update(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error)
	UpdateProductCountStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error)
	Trashed(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDeleteAt, error)
	Restore(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDeleteAt, error)
	DeleteProductPermanent(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDelete, error)
	RestoreAllProduct(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseProductAll, error)
	DeleteAllProduct(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseProductAll, error)
}

type productCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductCommandServiceClient(cc grpc.ClientConnInterface) ProductCommandServiceClient {
	return &productCommandServiceClient{cc}
}

func (c *productCommandServiceClient) Create(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProduct)
	err := c.cc.Invoke(ctx, ProductCommandService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) Update(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProduct)
	err := c.cc.Invoke(ctx, ProductCommandService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) UpdateProductCountStock(ctx context.Context, in *UpdateProductStockRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProduct)
	err := c.cc.Invoke(ctx, ProductCommandService_UpdateProductCountStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) Trashed(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductDeleteAt)
	err := c.cc.Invoke(ctx, ProductCommandService_Trashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) Restore(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductDeleteAt)
	err := c.cc.Invoke(ctx, ProductCommandService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) DeleteProductPermanent(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProductDelete, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductDelete)
	err := c.cc.Invoke(ctx, ProductCommandService_DeleteProductPermanent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) RestoreAllProduct(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseProductAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductAll)
	err := c.cc.Invoke(ctx, ProductCommandService_RestoreAllProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productCommandServiceClient) DeleteAllProduct(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ApiResponseProductAll, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProductAll)
	err := c.cc.Invoke(ctx, ProductCommandService_DeleteAllProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductCommandServiceServer is the server API for ProductCommandService service.
// All implementations must embed UnimplementedProductCommandServiceServer
// for forward compatibility.
type ProductCommandServiceServer interface {
	Create(context.Context, *CreateProductRequest) (*ApiResponseProduct, error)
	Update(context.Context, *UpdateProductRequest) (*ApiResponseProduct, error)
	UpdateProductCountStock(context.Context, *UpdateProductStockRequest) (*ApiResponseProduct, error)
	Trashed(context.Context, *FindByIdProductRequest) (*ApiResponseProductDeleteAt, error)
	Restore(context.Context, *FindByIdProductRequest) (*ApiResponseProductDeleteAt, error)
	DeleteProductPermanent(context.Context, *FindByIdProductRequest) (*ApiResponseProductDelete, error)
	RestoreAllProduct(context.Context, *emptypb.Empty) (*ApiResponseProductAll, error)
	DeleteAllProduct(context.Context, *emptypb.Empty) (*ApiResponseProductAll, error)
	mustEmbedUnimplementedProductCommandServiceServer()
}

// UnimplementedProductCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductCommandServiceServer struct{}

func (UnimplementedProductCommandServiceServer) Create(context.Context, *CreateProductRequest) (*ApiResponseProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedProductCommandServiceServer) Update(context.Context, *UpdateProductRequest) (*ApiResponseProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedProductCommandServiceServer) UpdateProductCountStock(context.Context, *UpdateProductStockRequest) (*ApiResponseProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProductCountStock not implemented")
}
func (UnimplementedProductCommandServiceServer) Trashed(context.Context, *FindByIdProductRequest) (*ApiResponseProductDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trashed not implemented")
}
func (UnimplementedProductCommandServiceServer) Restore(context.Context, *FindByIdProductRequest) (*ApiResponseProductDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedProductCommandServiceServer) DeleteProductPermanent(context.Context, *FindByIdProductRequest) (*ApiResponseProductDelete, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductPermanent not implemented")
}
func (UnimplementedProductCommandServiceServer) RestoreAllProduct(context.Context, *emptypb.Empty) (*ApiResponseProductAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreAllProduct not implemented")
}
func (UnimplementedProductCommandServiceServer) DeleteAllProduct(context.Context, *emptypb.Empty) (*ApiResponseProductAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllProduct not implemented")
}
func (UnimplementedProductCommandServiceServer) mustEmbedUnimplementedProductCommandServiceServer() {}
func (UnimplementedProductCommandServiceServer) testEmbeddedByValue()                               {}

// UnsafeProductCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductCommandServiceServer will
// result in compilation errors.
type UnsafeProductCommandServiceServer interface {
	mustEmbedUnimplementedProductCommandServiceServer()
}

func RegisterProductCommandServiceServer(s grpc.ServiceRegistrar, srv ProductCommandServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductCommandService_ServiceDesc, srv)
}

func _ProductCommandService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).Create(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).Update(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_UpdateProductCountStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).UpdateProductCountStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_UpdateProductCountStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).UpdateProductCountStock(ctx, req.(*UpdateProductStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_Trashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).Trashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_Trashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).Trashed(ctx, req.(*FindByIdProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).Restore(ctx, req.(*FindByIdProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_DeleteProductPermanent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).DeleteProductPermanent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_DeleteProductPermanent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).DeleteProductPermanent(ctx, req.(*FindByIdProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_RestoreAllProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).RestoreAllProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_RestoreAllProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).RestoreAllProduct(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductCommandService_DeleteAllProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductCommandServiceServer).DeleteAllProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductCommandService_DeleteAllProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductCommandServiceServer).DeleteAllProduct(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductCommandService_ServiceDesc is the grpc.ServiceDesc for ProductCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.product.ProductCommandService",
	HandlerType: (*ProductCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProductCommandService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProductCommandService_Update_Handler,
		},
		{
			MethodName: "UpdateProductCountStock",
			Handler:    _ProductCommandService_UpdateProductCountStock_Handler,
		},
		{
			MethodName: "Trashed",
			Handler:    _ProductCommandService_Trashed_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _ProductCommandService_Restore_Handler,
		},
		{
			MethodName: "DeleteProductPermanent",
			Handler:    _ProductCommandService_DeleteProductPermanent_Handler,
		},
		{
			MethodName: "RestoreAllProduct",
			Handler:    _ProductCommandService_RestoreAllProduct_Handler,
		},
		{
			MethodName: "DeleteAllProduct",
			Handler:    _ProductCommandService_DeleteAllProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/command.proto",
}
