// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: product/query.proto

package product

import (
	simple_microservice_ecommerce_pb "github.com/MamangRust/simple_microservice_ecommerce_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllProductRequest) Reset() {
	*x = FindAllProductRequest{}
	mi := &file_product_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllProductRequest) ProtoMessage() {}

func (x *FindAllProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllProductRequest.ProtoReflect.Descriptor instead.
func (*FindAllProductRequest) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllProductRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllProductRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllProductRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ApiResponsePaginationProductDeleteAt struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Status        string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ProductResponseDeleteAt                   `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationProductDeleteAt) Reset() {
	*x = ApiResponsePaginationProductDeleteAt{}
	mi := &file_product_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationProductDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationProductDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationProductDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationProductDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationProductDeleteAt) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponsePaginationProductDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationProductDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationProductDeleteAt) GetData() []*ProductResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationProductDeleteAt) GetPagination() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationProduct struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Status        string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*ProductResponse                           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationProduct) Reset() {
	*x = ApiResponsePaginationProduct{}
	mi := &file_product_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationProduct) ProtoMessage() {}

func (x *ApiResponsePaginationProduct) ProtoReflect() protoreflect.Message {
	mi := &file_product_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationProduct.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationProduct) Descriptor() ([]byte, []int) {
	return file_product_query_proto_rawDescGZIP(), []int{2}
}

func (x *ApiResponsePaginationProduct) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationProduct) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationProduct) GetData() []*ProductResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationProduct) GetPagination() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_product_query_proto protoreflect.FileDescriptor

const file_product_query_proto_rawDesc = "" +
	"\n" +
	"\x13product/query.proto\x12\n" +
	"pb.product\x1a\tapi.proto\x1a\x14product/common.proto\"`\n" +
	"\x15FindAllProductRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\xc1\x01\n" +
	"$ApiResponsePaginationProductDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.pb.product.ProductResponseDeleteAtR\x04data\x12.\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination\"\xb1\x01\n" +
	"\x1cApiResponsePaginationProduct\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\x04data\x18\x03 \x03(\v2\x1b.pb.product.ProductResponseR\x04data\x12.\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination2\x88\x03\n" +
	"\x13ProductQueryService\x12V\n" +
	"\aFindAll\x12!.pb.product.FindAllProductRequest\x1a(.pb.product.ApiResponsePaginationProduct\x12N\n" +
	"\bFindById\x12\".pb.product.FindByIdProductRequest\x1a\x1e.pb.product.ApiResponseProduct\x12c\n" +
	"\fFindByActive\x12!.pb.product.FindAllProductRequest\x1a0.pb.product.ApiResponsePaginationProductDeleteAt\x12d\n" +
	"\rFindByTrashed\x12!.pb.product.FindAllProductRequest\x1a0.pb.product.ApiResponsePaginationProductDeleteAtB@Z>github.com/MamangRust/simple_microservice_ecommerce_pb/productb\x06proto3"

var (
	file_product_query_proto_rawDescOnce sync.Once
	file_product_query_proto_rawDescData []byte
)

func file_product_query_proto_rawDescGZIP() []byte {
	file_product_query_proto_rawDescOnce.Do(func() {
		file_product_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_query_proto_rawDesc), len(file_product_query_proto_rawDesc)))
	})
	return file_product_query_proto_rawDescData
}

var file_product_query_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_product_query_proto_goTypes = []any{
	(*FindAllProductRequest)(nil),                       // 0: pb.product.FindAllProductRequest
	(*ApiResponsePaginationProductDeleteAt)(nil),        // 1: pb.product.ApiResponsePaginationProductDeleteAt
	(*ApiResponsePaginationProduct)(nil),                // 2: pb.product.ApiResponsePaginationProduct
	(*ProductResponseDeleteAt)(nil),                     // 3: pb.product.ProductResponseDeleteAt
	(*simple_microservice_ecommerce_pb.Pagination)(nil), // 4: pb.Pagination
	(*ProductResponse)(nil),                             // 5: pb.product.ProductResponse
	(*FindByIdProductRequest)(nil),                      // 6: pb.product.FindByIdProductRequest
	(*ApiResponseProduct)(nil),                          // 7: pb.product.ApiResponseProduct
}
var file_product_query_proto_depIdxs = []int32{
	3, // 0: pb.product.ApiResponsePaginationProductDeleteAt.data:type_name -> pb.product.ProductResponseDeleteAt
	4, // 1: pb.product.ApiResponsePaginationProductDeleteAt.pagination:type_name -> pb.Pagination
	5, // 2: pb.product.ApiResponsePaginationProduct.data:type_name -> pb.product.ProductResponse
	4, // 3: pb.product.ApiResponsePaginationProduct.pagination:type_name -> pb.Pagination
	0, // 4: pb.product.ProductQueryService.FindAll:input_type -> pb.product.FindAllProductRequest
	6, // 5: pb.product.ProductQueryService.FindById:input_type -> pb.product.FindByIdProductRequest
	0, // 6: pb.product.ProductQueryService.FindByActive:input_type -> pb.product.FindAllProductRequest
	0, // 7: pb.product.ProductQueryService.FindByTrashed:input_type -> pb.product.FindAllProductRequest
	2, // 8: pb.product.ProductQueryService.FindAll:output_type -> pb.product.ApiResponsePaginationProduct
	7, // 9: pb.product.ProductQueryService.FindById:output_type -> pb.product.ApiResponseProduct
	1, // 10: pb.product.ProductQueryService.FindByActive:output_type -> pb.product.ApiResponsePaginationProductDeleteAt
	1, // 11: pb.product.ProductQueryService.FindByTrashed:output_type -> pb.product.ApiResponsePaginationProductDeleteAt
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_product_query_proto_init() }
func file_product_query_proto_init() {
	if File_product_query_proto != nil {
		return
	}
	file_product_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_query_proto_rawDesc), len(file_product_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_query_proto_goTypes,
		DependencyIndexes: file_product_query_proto_depIdxs,
		MessageInfos:      file_product_query_proto_msgTypes,
	}.Build()
	File_product_query_proto = out.File
	file_product_query_proto_goTypes = nil
	file_product_query_proto_depIdxs = nil
}
