// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: product/query.proto

package product

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductQueryService_FindAll_FullMethodName       = "/pb.product.ProductQueryService/FindAll"
	ProductQueryService_FindById_FullMethodName      = "/pb.product.ProductQueryService/FindById"
	ProductQueryService_FindByActive_FullMethodName  = "/pb.product.ProductQueryService/FindByActive"
	ProductQueryService_FindByTrashed_FullMethodName = "/pb.product.ProductQueryService/FindByTrashed"
)

// ProductQueryServiceClient is the client API for ProductQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductQueryServiceClient interface {
	FindAll(ctx context.Context, in *FindAllProductRequest, opts ...grpc.CallOption) (*ApiResponsePaginationProduct, error)
	FindById(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error)
	FindByActive(ctx context.Context, in *FindAllProductRequest, opts ...grpc.CallOption) (*ApiResponsePaginationProductDeleteAt, error)
	FindByTrashed(ctx context.Context, in *FindAllProductRequest, opts ...grpc.CallOption) (*ApiResponsePaginationProductDeleteAt, error)
}

type productQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductQueryServiceClient(cc grpc.ClientConnInterface) ProductQueryServiceClient {
	return &productQueryServiceClient{cc}
}

func (c *productQueryServiceClient) FindAll(ctx context.Context, in *FindAllProductRequest, opts ...grpc.CallOption) (*ApiResponsePaginationProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationProduct)
	err := c.cc.Invoke(ctx, ProductQueryService_FindAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productQueryServiceClient) FindById(ctx context.Context, in *FindByIdProductRequest, opts ...grpc.CallOption) (*ApiResponseProduct, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponseProduct)
	err := c.cc.Invoke(ctx, ProductQueryService_FindById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productQueryServiceClient) FindByActive(ctx context.Context, in *FindAllProductRequest, opts ...grpc.CallOption) (*ApiResponsePaginationProductDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationProductDeleteAt)
	err := c.cc.Invoke(ctx, ProductQueryService_FindByActive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productQueryServiceClient) FindByTrashed(ctx context.Context, in *FindAllProductRequest, opts ...grpc.CallOption) (*ApiResponsePaginationProductDeleteAt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApiResponsePaginationProductDeleteAt)
	err := c.cc.Invoke(ctx, ProductQueryService_FindByTrashed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductQueryServiceServer is the server API for ProductQueryService service.
// All implementations must embed UnimplementedProductQueryServiceServer
// for forward compatibility.
type ProductQueryServiceServer interface {
	FindAll(context.Context, *FindAllProductRequest) (*ApiResponsePaginationProduct, error)
	FindById(context.Context, *FindByIdProductRequest) (*ApiResponseProduct, error)
	FindByActive(context.Context, *FindAllProductRequest) (*ApiResponsePaginationProductDeleteAt, error)
	FindByTrashed(context.Context, *FindAllProductRequest) (*ApiResponsePaginationProductDeleteAt, error)
	mustEmbedUnimplementedProductQueryServiceServer()
}

// UnimplementedProductQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductQueryServiceServer struct{}

func (UnimplementedProductQueryServiceServer) FindAll(context.Context, *FindAllProductRequest) (*ApiResponsePaginationProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedProductQueryServiceServer) FindById(context.Context, *FindByIdProductRequest) (*ApiResponseProduct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}
func (UnimplementedProductQueryServiceServer) FindByActive(context.Context, *FindAllProductRequest) (*ApiResponsePaginationProductDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByActive not implemented")
}
func (UnimplementedProductQueryServiceServer) FindByTrashed(context.Context, *FindAllProductRequest) (*ApiResponsePaginationProductDeleteAt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByTrashed not implemented")
}
func (UnimplementedProductQueryServiceServer) mustEmbedUnimplementedProductQueryServiceServer() {}
func (UnimplementedProductQueryServiceServer) testEmbeddedByValue()                             {}

// UnsafeProductQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductQueryServiceServer will
// result in compilation errors.
type UnsafeProductQueryServiceServer interface {
	mustEmbedUnimplementedProductQueryServiceServer()
}

func RegisterProductQueryServiceServer(s grpc.ServiceRegistrar, srv ProductQueryServiceServer) {
	// If the following call pancis, it indicates UnimplementedProductQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductQueryService_ServiceDesc, srv)
}

func _ProductQueryService_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductQueryServiceServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductQueryService_FindAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductQueryServiceServer).FindAll(ctx, req.(*FindAllProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductQueryService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByIdProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductQueryServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductQueryService_FindById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductQueryServiceServer).FindById(ctx, req.(*FindByIdProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductQueryService_FindByActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductQueryServiceServer).FindByActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductQueryService_FindByActive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductQueryServiceServer).FindByActive(ctx, req.(*FindAllProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductQueryService_FindByTrashed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductQueryServiceServer).FindByTrashed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductQueryService_FindByTrashed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductQueryServiceServer).FindByTrashed(ctx, req.(*FindAllProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductQueryService_ServiceDesc is the grpc.ServiceDesc for ProductQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.product.ProductQueryService",
	HandlerType: (*ProductQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _ProductQueryService_FindAll_Handler,
		},
		{
			MethodName: "FindById",
			Handler:    _ProductQueryService_FindById_Handler,
		},
		{
			MethodName: "FindByActive",
			Handler:    _ProductQueryService_FindByActive_Handler,
		},
		{
			MethodName: "FindByTrashed",
			Handler:    _ProductQueryService_FindByTrashed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product/query.proto",
}
