// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: user/command.proto

package user

import (
	auth "github.com/MamangRust/simple_microservice_ecommerce_pb/auth"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Firstname       string                 `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname        string                 `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,5,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_command_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *CreateUserRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type UpdateUserVerifiedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsVerified    bool                   `protobuf:"varint,2,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserVerifiedRequest) Reset() {
	*x = UpdateUserVerifiedRequest{}
	mi := &file_user_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserVerifiedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserVerifiedRequest) ProtoMessage() {}

func (x *UpdateUserVerifiedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserVerifiedRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserVerifiedRequest) Descriptor() ([]byte, []int) {
	return file_user_command_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateUserVerifiedRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserVerifiedRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type UpdateUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserPasswordRequest) Reset() {
	*x = UpdateUserPasswordRequest{}
	mi := &file_user_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserPasswordRequest) ProtoMessage() {}

func (x *UpdateUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_command_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserPasswordRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateUserRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname       string                 `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname        string                 `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email           string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,6,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_command_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *UpdateUserRequest) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type ApiResponseUserDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseUserDelete) Reset() {
	*x = ApiResponseUserDelete{}
	mi := &file_user_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseUserDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseUserDelete) ProtoMessage() {}

func (x *ApiResponseUserDelete) ProtoReflect() protoreflect.Message {
	mi := &file_user_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseUserDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseUserDelete) Descriptor() ([]byte, []int) {
	return file_user_command_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponseUserDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseUserDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseUserAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseUserAll) Reset() {
	*x = ApiResponseUserAll{}
	mi := &file_user_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseUserAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseUserAll) ProtoMessage() {}

func (x *ApiResponseUserAll) ProtoReflect() protoreflect.Message {
	mi := &file_user_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseUserAll.ProtoReflect.Descriptor instead.
func (*ApiResponseUserAll) Descriptor() ([]byte, []int) {
	return file_user_command_proto_rawDescGZIP(), []int{5}
}

func (x *ApiResponseUserAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseUserAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_user_command_proto protoreflect.FileDescriptor

const file_user_command_proto_rawDesc = "" +
	"\n" +
	"\x12user/command.proto\x12\apb.user\x1a\x1bgoogle/protobuf/empty.proto\x1a\x11user/common.proto\x1a\x0fauth/auth.proto\"\xaa\x01\n" +
	"\x11CreateUserRequest\x12\x1c\n" +
	"\tfirstname\x18\x01 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x02 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x05 \x01(\tR\x0fconfirmPassword\"U\n" +
	"\x19UpdateUserVerifiedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vis_verified\x18\x02 \x01(\bR\n" +
	"isVerified\"P\n" +
	"\x19UpdateUserPasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xba\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tfirstname\x18\x02 \x01(\tR\tfirstname\x12\x1a\n" +
	"\blastname\x18\x03 \x01(\tR\blastname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x06 \x01(\tR\x0fconfirmPassword\"I\n" +
	"\x15ApiResponseUserDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"F\n" +
	"\x12ApiResponseUserAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd1\x05\n" +
	"\x12UserCommandService\x12@\n" +
	"\n" +
	"CreateUser\x12\x18.pb.auth.RegisterRequest\x1a\x18.pb.user.ApiResponseUser\x12B\n" +
	"\n" +
	"UpdateUser\x12\x1a.pb.user.UpdateUserRequest\x1a\x18.pb.user.ApiResponseUser\x12M\n" +
	"\vTrashedUser\x12\x1c.pb.user.FindByIdUserRequest\x1a .pb.user.ApiResponseUserDeleteAt\x12M\n" +
	"\vRestoreUser\x12\x1c.pb.user.FindByIdUserRequest\x1a .pb.user.ApiResponseUserDeleteAt\x12S\n" +
	"\x13DeleteUserPermanent\x12\x1c.pb.user.FindByIdUserRequest\x1a\x1e.pb.user.ApiResponseUserDelete\x12T\n" +
	"\x14UpdateUserIsVerified\x12\".pb.user.UpdateUserVerifiedRequest\x1a\x18.pb.user.ApiResponseUser\x12R\n" +
	"\x12UpdateUserPassword\x12\".pb.user.UpdateUserPasswordRequest\x1a\x18.pb.user.ApiResponseUser\x12G\n" +
	"\x0eRestoreAllUser\x12\x16.google.protobuf.Empty\x1a\x1b.pb.user.ApiResponseUserAll\"\x00\x12O\n" +
	"\x16DeleteAllUserPermanent\x12\x16.google.protobuf.Empty\x1a\x1b.pb.user.ApiResponseUserAll\"\x00B=Z;github.com/MamangRust/simple_microservice_ecommerce_pb/userb\x06proto3"

var (
	file_user_command_proto_rawDescOnce sync.Once
	file_user_command_proto_rawDescData []byte
)

func file_user_command_proto_rawDescGZIP() []byte {
	file_user_command_proto_rawDescOnce.Do(func() {
		file_user_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_command_proto_rawDesc), len(file_user_command_proto_rawDesc)))
	})
	return file_user_command_proto_rawDescData
}

var file_user_command_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_user_command_proto_goTypes = []any{
	(*CreateUserRequest)(nil),         // 0: pb.user.CreateUserRequest
	(*UpdateUserVerifiedRequest)(nil), // 1: pb.user.UpdateUserVerifiedRequest
	(*UpdateUserPasswordRequest)(nil), // 2: pb.user.UpdateUserPasswordRequest
	(*UpdateUserRequest)(nil),         // 3: pb.user.UpdateUserRequest
	(*ApiResponseUserDelete)(nil),     // 4: pb.user.ApiResponseUserDelete
	(*ApiResponseUserAll)(nil),        // 5: pb.user.ApiResponseUserAll
	(*auth.RegisterRequest)(nil),      // 6: pb.auth.RegisterRequest
	(*FindByIdUserRequest)(nil),       // 7: pb.user.FindByIdUserRequest
	(*emptypb.Empty)(nil),             // 8: google.protobuf.Empty
	(*ApiResponseUser)(nil),           // 9: pb.user.ApiResponseUser
	(*ApiResponseUserDeleteAt)(nil),   // 10: pb.user.ApiResponseUserDeleteAt
}
var file_user_command_proto_depIdxs = []int32{
	6,  // 0: pb.user.UserCommandService.CreateUser:input_type -> pb.auth.RegisterRequest
	3,  // 1: pb.user.UserCommandService.UpdateUser:input_type -> pb.user.UpdateUserRequest
	7,  // 2: pb.user.UserCommandService.TrashedUser:input_type -> pb.user.FindByIdUserRequest
	7,  // 3: pb.user.UserCommandService.RestoreUser:input_type -> pb.user.FindByIdUserRequest
	7,  // 4: pb.user.UserCommandService.DeleteUserPermanent:input_type -> pb.user.FindByIdUserRequest
	1,  // 5: pb.user.UserCommandService.UpdateUserIsVerified:input_type -> pb.user.UpdateUserVerifiedRequest
	2,  // 6: pb.user.UserCommandService.UpdateUserPassword:input_type -> pb.user.UpdateUserPasswordRequest
	8,  // 7: pb.user.UserCommandService.RestoreAllUser:input_type -> google.protobuf.Empty
	8,  // 8: pb.user.UserCommandService.DeleteAllUserPermanent:input_type -> google.protobuf.Empty
	9,  // 9: pb.user.UserCommandService.CreateUser:output_type -> pb.user.ApiResponseUser
	9,  // 10: pb.user.UserCommandService.UpdateUser:output_type -> pb.user.ApiResponseUser
	10, // 11: pb.user.UserCommandService.TrashedUser:output_type -> pb.user.ApiResponseUserDeleteAt
	10, // 12: pb.user.UserCommandService.RestoreUser:output_type -> pb.user.ApiResponseUserDeleteAt
	4,  // 13: pb.user.UserCommandService.DeleteUserPermanent:output_type -> pb.user.ApiResponseUserDelete
	9,  // 14: pb.user.UserCommandService.UpdateUserIsVerified:output_type -> pb.user.ApiResponseUser
	9,  // 15: pb.user.UserCommandService.UpdateUserPassword:output_type -> pb.user.ApiResponseUser
	5,  // 16: pb.user.UserCommandService.RestoreAllUser:output_type -> pb.user.ApiResponseUserAll
	5,  // 17: pb.user.UserCommandService.DeleteAllUserPermanent:output_type -> pb.user.ApiResponseUserAll
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_user_command_proto_init() }
func file_user_command_proto_init() {
	if File_user_command_proto != nil {
		return
	}
	file_user_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_command_proto_rawDesc), len(file_user_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_command_proto_goTypes,
		DependencyIndexes: file_user_command_proto_depIdxs,
		MessageInfos:      file_user_command_proto_msgTypes,
	}.Build()
	File_user_command_proto = out.File
	file_user_command_proto_goTypes = nil
	file_user_command_proto_depIdxs = nil
}
