// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: user/query.proto

package user

import (
	simple_microservice_ecommerce_pb "github.com/MamangRust/simple_microservice_ecommerce_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindAllUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllUserRequest) Reset() {
	*x = FindAllUserRequest{}
	mi := &file_user_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllUserRequest) ProtoMessage() {}

func (x *FindAllUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllUserRequest.ProtoReflect.Descriptor instead.
func (*FindAllUserRequest) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{0}
}

func (x *FindAllUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllUserRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllUserRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByEmailUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByEmailUserRequest) Reset() {
	*x = FindByEmailUserRequest{}
	mi := &file_user_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByEmailUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByEmailUserRequest) ProtoMessage() {}

func (x *FindByEmailUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByEmailUserRequest.ProtoReflect.Descriptor instead.
func (*FindByEmailUserRequest) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{1}
}

func (x *FindByEmailUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type VerifyCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCodeRequest) Reset() {
	*x = VerifyCodeRequest{}
	mi := &file_user_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRequest) ProtoMessage() {}

func (x *VerifyCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ApiResponsePaginationUserDeleteAt struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Status        string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*UserResponseDeleteAt                      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationUserDeleteAt) Reset() {
	*x = ApiResponsePaginationUserDeleteAt{}
	mi := &file_user_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationUserDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationUserDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationUserDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationUserDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationUserDeleteAt) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{3}
}

func (x *ApiResponsePaginationUserDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationUserDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationUserDeleteAt) GetData() []*UserResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationUserDeleteAt) GetPagination() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationUser struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Status        string                                       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*UserResponse                              `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *simple_microservice_ecommerce_pb.Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationUser) Reset() {
	*x = ApiResponsePaginationUser{}
	mi := &file_user_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationUser) ProtoMessage() {}

func (x *ApiResponsePaginationUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationUser.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationUser) Descriptor() ([]byte, []int) {
	return file_user_query_proto_rawDescGZIP(), []int{4}
}

func (x *ApiResponsePaginationUser) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationUser) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationUser) GetData() []*UserResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationUser) GetPagination() *simple_microservice_ecommerce_pb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_user_query_proto protoreflect.FileDescriptor

const file_user_query_proto_rawDesc = "" +
	"\n" +
	"\x10user/query.proto\x12\apb.user\x1a\tapi.proto\x1a\x11user/common.proto\"]\n" +
	"\x12FindAllUserRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\".\n" +
	"\x16FindByEmailUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"'\n" +
	"\x11VerifyCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xb8\x01\n" +
	"!ApiResponsePaginationUserDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x04data\x18\x03 \x03(\v2\x1d.pb.user.UserResponseDeleteAtR\x04data\x12.\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination\"\xa8\x01\n" +
	"\x19ApiResponsePaginationUser\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04data\x18\x03 \x03(\v2\x15.pb.user.UserResponseR\x04data\x12.\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x0e.pb.PaginationR\n" +
	"pagination2\xd0\x04\n" +
	"\x10UserQueryService\x12J\n" +
	"\aFindAll\x12\x1b.pb.user.FindAllUserRequest\x1a\".pb.user.ApiResponsePaginationUser\x12B\n" +
	"\bFindById\x12\x1c.pb.user.FindByIdUserRequest\x1a\x18.pb.user.ApiResponseUser\x12Y\n" +
	"\fFindByActive\x12\x1b.pb.user.FindAllUserRequest\x1a*.pb.user.ApiResponsePaginationUserDeleteAt\"\x00\x12Z\n" +
	"\rFindByTrashed\x12\x1b.pb.user.FindAllUserRequest\x1a*.pb.user.ApiResponsePaginationUserDeleteAt\"\x00\x12H\n" +
	"\vFindByEmail\x12\x1f.pb.user.FindByEmailUserRequest\x1a\x18.pb.user.ApiResponseUser\x12]\n" +
	"\x14FindByEmailAndVerify\x12\x1f.pb.user.FindByEmailUserRequest\x1a$.pb.user.ApiResponseUserWithPassword\x12L\n" +
	"\x14FindVerificationCode\x12\x1a.pb.user.VerifyCodeRequest\x1a\x18.pb.user.ApiResponseUserB=Z;github.com/MamangRust/simple_microservice_ecommerce_pb/userb\x06proto3"

var (
	file_user_query_proto_rawDescOnce sync.Once
	file_user_query_proto_rawDescData []byte
)

func file_user_query_proto_rawDescGZIP() []byte {
	file_user_query_proto_rawDescOnce.Do(func() {
		file_user_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_query_proto_rawDesc), len(file_user_query_proto_rawDesc)))
	})
	return file_user_query_proto_rawDescData
}

var file_user_query_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_query_proto_goTypes = []any{
	(*FindAllUserRequest)(nil),                          // 0: pb.user.FindAllUserRequest
	(*FindByEmailUserRequest)(nil),                      // 1: pb.user.FindByEmailUserRequest
	(*VerifyCodeRequest)(nil),                           // 2: pb.user.VerifyCodeRequest
	(*ApiResponsePaginationUserDeleteAt)(nil),           // 3: pb.user.ApiResponsePaginationUserDeleteAt
	(*ApiResponsePaginationUser)(nil),                   // 4: pb.user.ApiResponsePaginationUser
	(*UserResponseDeleteAt)(nil),                        // 5: pb.user.UserResponseDeleteAt
	(*simple_microservice_ecommerce_pb.Pagination)(nil), // 6: pb.Pagination
	(*UserResponse)(nil),                                // 7: pb.user.UserResponse
	(*FindByIdUserRequest)(nil),                         // 8: pb.user.FindByIdUserRequest
	(*ApiResponseUser)(nil),                             // 9: pb.user.ApiResponseUser
	(*ApiResponseUserWithPassword)(nil),                 // 10: pb.user.ApiResponseUserWithPassword
}
var file_user_query_proto_depIdxs = []int32{
	5,  // 0: pb.user.ApiResponsePaginationUserDeleteAt.data:type_name -> pb.user.UserResponseDeleteAt
	6,  // 1: pb.user.ApiResponsePaginationUserDeleteAt.pagination:type_name -> pb.Pagination
	7,  // 2: pb.user.ApiResponsePaginationUser.data:type_name -> pb.user.UserResponse
	6,  // 3: pb.user.ApiResponsePaginationUser.pagination:type_name -> pb.Pagination
	0,  // 4: pb.user.UserQueryService.FindAll:input_type -> pb.user.FindAllUserRequest
	8,  // 5: pb.user.UserQueryService.FindById:input_type -> pb.user.FindByIdUserRequest
	0,  // 6: pb.user.UserQueryService.FindByActive:input_type -> pb.user.FindAllUserRequest
	0,  // 7: pb.user.UserQueryService.FindByTrashed:input_type -> pb.user.FindAllUserRequest
	1,  // 8: pb.user.UserQueryService.FindByEmail:input_type -> pb.user.FindByEmailUserRequest
	1,  // 9: pb.user.UserQueryService.FindByEmailAndVerify:input_type -> pb.user.FindByEmailUserRequest
	2,  // 10: pb.user.UserQueryService.FindVerificationCode:input_type -> pb.user.VerifyCodeRequest
	4,  // 11: pb.user.UserQueryService.FindAll:output_type -> pb.user.ApiResponsePaginationUser
	9,  // 12: pb.user.UserQueryService.FindById:output_type -> pb.user.ApiResponseUser
	3,  // 13: pb.user.UserQueryService.FindByActive:output_type -> pb.user.ApiResponsePaginationUserDeleteAt
	3,  // 14: pb.user.UserQueryService.FindByTrashed:output_type -> pb.user.ApiResponsePaginationUserDeleteAt
	9,  // 15: pb.user.UserQueryService.FindByEmail:output_type -> pb.user.ApiResponseUser
	10, // 16: pb.user.UserQueryService.FindByEmailAndVerify:output_type -> pb.user.ApiResponseUserWithPassword
	9,  // 17: pb.user.UserQueryService.FindVerificationCode:output_type -> pb.user.ApiResponseUser
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_user_query_proto_init() }
func file_user_query_proto_init() {
	if File_user_query_proto != nil {
		return
	}
	file_user_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_query_proto_rawDesc), len(file_user_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_query_proto_goTypes,
		DependencyIndexes: file_user_query_proto_depIdxs,
		MessageInfos:      file_user_query_proto_msgTypes,
	}.Build()
	File_user_query_proto = out.File
	file_user_query_proto_goTypes = nil
	file_user_query_proto_depIdxs = nil
}
